### ISSUE TITLE
removing build directory prevents rebuild/reinstallation

### ISSUE THREAD

**Issue by ckuethe** [gnuradio/pybombs#112]
While I was figuring out why gr-baz was trying to compile/install armadillo (missing satisfy-deb libarmadillo-dev) I found that  removing a build directory prevents me from being able to rebuild and reinstall a package...

~/Development/gnuradio/pybombs$ rm -rf src/gr-baz/build/
~/Development/gnuradio/pybombs$ ./app_store.py 
Settled on prefix: /home/ckuethe/gnuradio
Initializing environmental variables...
/home/ckuethe/gnuradio/python/:/home/ckuethe/gnuradio/lib/python2.6/site-packages/:/home/ckuethe/gnuradio/lib64/python2.6/site-packages/:/home/ckuethe/gnuradio/lib/python2.6/dist-packages/:/home/ckuethe/gnuradio/lib64/python2.6/dist-packages/:/home/ckuethe/gnuradio/lib/python2.7/site-packages/:/home/ckuethe/gnuradio/lib64/python2.7/site-packages/:/home/ckuethe/gnuradio/lib/python2.7/dist-packages/:/home/ckuethe/gnuradio/lib64/python2.7/dist-packages/:/home/ckuethe/gnuradio/python/:/home/ckuethe/gnuradio/lib/python2.6/site-packages/:/home/ckuethe/gnuradio/lib64/python2.6/site-packages/:/home/ckuethe/gnuradio/lib/python2.6/dist-packages/:/home/ckuethe/gnuradio/lib64/python2.6/dist-packages/:/home/ckuethe/gnuradio/lib/python2.7/site-packages/:/home/ckuethe/gnuradio/lib64/python2.7/site-packages/:/home/ckuethe/gnuradio/lib/python2.7/dist-packages/:/home/ckuethe/gnuradio/lib64/python2.7/dist-packages/
Loading recipes ...
Loading recipes ... done
installing gr-baz
TMPFILE = /home/ckuethe/gnuradio/tmpYBu02c
WRITE PERMS OK /home/ckuethe/gnuradio
installing gr-baz
gr-baz dep [['gnuradio', 'uhd', 'curl', 'cmake', 'armadillo', 'gr-compat', 'git', 'cmake']]
gnuradio dep [['make', 'boost', 'fftw', 'cppunit', 'swig', 'gsl', 'uhd', 'alsa', 'git', 'python', 'cheetah', 'wxpython', 'numpy', 'lxml', 'pygtk', 'pycairo', 'cmake', 'pyqt4', 'pyqwt5', 'gcc', 'ice', 'git', 'cmake']]
uhd dep [['make', 'swig', 'python', 'libusb', 'git', 'cmake', 'cheetah', 'boost', 'gsl', 'numpy', 'cppunit', 'fftw', 'git', 'cmake']]
curl dep [[]]
cmake dep [['wget']]
PyBombs.sysutils - INFO - have_deb: Satisfies requirement...installed version of cmake (2.8.12) is >= than 2.8.3
PyBombs.sysutils - INFO - have_deb: Satisfies requirement...installed version of cmake-data (2.8.12) is >= than 2.8.3
armadillo dep [['wget', 'cmake', 'blas', 'lapack', 'cmake']]
gr-compat dep [['gnuradio', 'git', 'cmake']]
git dep [['wget', 'curl']]
cmake dep [['wget']]
packages to install: ['gr-baz']
install called (gr-baz)
install type priority: ['deb', 'src']
install deb called (gr-baz)
no deb satisfiers available
install src called (gr-baz)
state = configure
Current step: (gr-baz :: make)
make
('\n    make -j4\n', '\n    make -j$makewidth\n')
('\n    make -j4\n', '\n    make -j4\n')
bash exec (/home/ckuethe/Development/gnuradio/pybombs/src/gr-baz/build):: 
    make -j4

make: *** No targets specified and no makefile found.  Stop.
ERROR:root:PyBOMBS Make step failed for package (gr-baz) please see bash output above for a reason (hint: look for the word Error)
~/Development/gnuradio/pybombs$

**Comment by misham** [comment]
any news on this?  I'm running into the same issue.  Running on BeagleBone Black rev C with the latest Debian image.

**Comment by mbr0wn** [comment]
I guess you probably shouldn't be nuking the build directory. We're currently working on a massive change in PyBOMBS, maybe we can come up with a cleverererer way to store inventory items, such as using the build dir.

**Comment by ckuethe** [comment]
Nuking the build (object, output, whatever) directory is a pretty reasonable thing to do. It frees disk space, you might need to do it to recover from a major system error, any number of other things.
