### ISSUE TITLE
RuntimeError

### ISSUE THREAD

**Issue by xxxajk** [gnuradio/pybombs#150]
```
# python2.6 app_store.py
Traceback (most recent call last):
  File "app_store.py", line 23, in <module>
    from PyQt4.QtCore import Qt;
RuntimeError: the sip module implements API v8.0 to v8.1 but the PyQt4.QtCore module requires API v7.1
```

**Comment by osh** [comment]
This sounds like a problem with your python and qt setup -

**Comment by xxxajk** [comment]
isn't. This is the only app that spits out this error. 
The 'sip' uses a higher api version, thus it isn't a problem with my installation, and no, I can't and won't update it. 
Can we use wx as an alternate?
e.g.
catch the import error, and use wxwidgets instead.
