### ISSUE TITLE
libosmocore doesn't build, needs libpcsc

### ISSUE THREAD

**Issue by qrah** [gnuradio/pybombs#159]
It can be fixed by doing this:

<pre>
From 5273fbe2df4381ea52be16279f4d1111dd41afe7 Mon Sep 17 00:00:00 2001
From: hark <hark@puscii.nl>
Date: Fri, 20 Mar 2015 16:38:26 +0100
Subject: [PATCH] no libpsc

---
 recipes/libosmocore.lwr | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/recipes/libosmocore.lwr b/recipes/libosmocore.lwr
index 415ae65..81197c6 100644
--- a/recipes/libosmocore.lwr
+++ b/recipes/libosmocore.lwr
@@ -27,6 +27,6 @@ inherit: autoconf

 configure {
     autoreconf -i
-    ./configure --prefix=$prefix $config_opt
+    ./configure --disable-pcsc --prefix=$prefix $config_opt
 }

-- 
2.1.4

</pre>

**Comment by ckuethe** [comment]
Fixed by https://github.com/gnuradio/recipes/pull/36  ... wherein pcsc was added as a dependency
