### ISSUE TITLE
After installing, how can I start gnuradio

### ISSUE THREAD

**Issue by franklinzhang** [gnuradio/pybombs#161]
I installed gnuradio successfully via pybombs. While after that I can't start gnuradio. 
I typed 
```
gnuradio-companion
```
or 
```
grc
```
in the terminal. But the system told me the gnuradio has not installed.

In python, I import gnuradio, it can't find gnuradio also.

Should I need more operations?

**Comment by mbr0wn** [comment]
Please ask support questions on the list. This is for bug reports only.
