### ISSUE TITLE
GQRX wont compile on Ubuntu 14.04 (LinuxMint) when boost requires -mt flag on pybombs

### ISSUE THREAD

**Issue by JannF** [gnuradio/pybombs#171]
As the title says, GQRX won't compile on Linux Mint (Ubuntu based) because it's recipe needs the boost library with -mt flag.
Removing -mt flag from the recipe lets me at least compile.

**Comment by ckuethe** [comment]
yep, i see this on ubuntu too and haven't figured out how to automatically detect the right suffix to use. sadly, there is no pkgconfig or "boost-config" support figure out how and where boost is installed.

**Comment by ckuethe** [comment]
https://github.com/csete/gqrx/issues/254

**Comment by Ka-zam** [comment]
The -mt suffix is unnecessary on as boost is thread safe. Perhaps it's safe to remove -mt from the recipe.

**Comment by ckuethe** [comment]
I concur. https://github.com/gnuradio/recipes/pull/38
