### ISSUE TITLE
Building apache-thrift, Pybombs on ubuntu 14.04 

### ISSUE THREAD

**Issue by abramhindle** [gnuradio/pybombs#191]
Apache-thrift now requires automake 1.13.

Ubuntu 14.04 comes with version 1.11.3.

Thrift reports:
    automake version 1.11.3 is too old (need 1.13 or later)

    root@23ea6420a2cf:/pybombs# ./pybombs install apache-thrift -vvv
    Settled on prefix: 
    Initializing environmental variables...
    ---------- loading recipes -------------------
    Loading recipes ...
    Loading recipes ... done
    ---------- loading recipes finished ----------
    
    Checking if apache-thrift is installed: No
    /
    TMPFILE = /tmpcJwrU9
    WRITE PERMS OK /tmpcJwrU9
    apache-thrift dep [['libtool', 'automake', 'gcc', 'boost', 'bison', 'flex', 'libevent', 'python', 'ssl', 'git']]
    libtool dep [[]]
    automake dep [[]]
    gcc dep [[]]
    boost dep [['python', 'libbzip', 'wget']]
    bison dep [['wget']]
    PyBombs.sysutils - INFO - have_deb: Satisfies requirement...installed version of bison (2.5) is >= than 2.3
    flex dep [['wget']]
    PyBombs.sysutils - INFO - have_deb: Satisfies requirement...installed version of flex (2.5.35) is >= than 2.5.35
    libevent dep [['ssl']]
    python dep [['wget']]
    ssl dep [[]]
    git dep [['wget', 'curl']]
    Installing packages:
    * apache-thrift
    install type priority: ['src']
    install src called (apache-thrift)
    Installing from source: apache-thrift
    [('fetch', <bound method recipe.fetch of <mod_pybombs.recipe.recipe instance at 0xeacab8>>), ('configure', <bound method recipe.configure of <mod_pybombs.recipe.recipe instance at 0xeacab8>>), ('make', <bound method recipe.make of <mod_pybombs.recipe.recipe instance at 0xeacab8>>), ('installed', <bound method recipe.installed of <mod_pybombs.recipe.recipe instance at 0xeacab8>>)]
    Current step: (apache-thrift :: configure)
    configure
    ('\n    ./bootstrap.sh && ./configure --prefix=/ \\\n    --with-c_glib --with-cpp --with-libevent --with-python \\\n    --without-csharp --without-d --without-erlang --without-go \\\n    --without-haskell --without-java --without-lua --without-nodejs \\\n    --without-perl --without-php --without-ruby --without-zlib \\\n    --disable-tests --disable-tutorial  \\\n    CC=gcc CXX=g++ PY_PREFIX=/ CXXFLAGS="-DNDEBUG"\n', '\n    ./bootstrap.sh && ./configure --prefix=$prefix \\\n    --with-c_glib --with-cpp --with-libevent --with-python \\\n    --without-csharp --without-d --without-erlang --without-go \\\n    --without-haskell --without-java --without-lua --without-nodejs \\\n    --without-perl --without-php --without-ruby --without-zlib \\\n    --disable-tests --disable-tutorial $config_opt \\\n    CC=$cc CXX=$cxx PY_PREFIX=$prefix CXXFLAGS="-DNDEBUG"\n')
    ('\n    ./bootstrap.sh && ./configure --prefix=/ \\\n    --with-c_glib --with-cpp --with-libevent --with-python \\\n    --without-csharp --without-d --without-erlang --without-go \\\n    --without-haskell --without-java --without-lua --without-nodejs \\\n    --without-perl --without-php --without-ruby --without-zlib \\\n    --disable-tests --disable-tutorial  \\\n    CC=gcc CXX=g++ PY_PREFIX=/ CXXFLAGS="-DNDEBUG"\n', '\n    ./bootstrap.sh && ./configure --prefix=/ \\\n    --with-c_glib --with-cpp --with-libevent --with-python \\\n    --without-csharp --without-d --without-erlang --without-go \\\n    --without-haskell --without-java --without-lua --without-nodejs \\\n    --without-perl --without-php --without-ruby --without-zlib \\\n    --disable-tests --disable-tutorial  \\\n    CC=gcc CXX=g++ PY_PREFIX=/ CXXFLAGS="-DNDEBUG"\n')
    
        ./bootstrap.sh && ./configure --prefix=/ \
        --with-c_glib --with-cpp --with-libevent --with-python \
        --without-csharp --without-d --without-erlang --without-go \
        --without-haskell --without-java --without-lua --without-nodejs \
        --without-perl --without-php --without-ruby --without-zlib \
        --disable-tests --disable-tutorial  \
        CC=gcc CXX=g++ PY_PREFIX=/ CXXFLAGS="-DNDEBUG"
    
    bash exec (/pybombs/src/apache-thrift):: ./bootstrap.sh && ./configure --prefix=/ \
        --with-c_glib --with-cpp --with-libevent --with-python \
        --without-csharp --without-d --without-erlang --without-go \
        --without-haskell --without-java --without-lua --without-nodejs \
        --without-perl --without-php --without-ruby --without-zlib \
        --disable-tests --disable-tutorial  \
        CC=gcc CXX=g++ PY_PREFIX=/ CXXFLAGS="-DNDEBUG"
    automake version 1.11.3 is too old (need 1.13 or later)
    bash return val = 1
    Configuration failed. Re-trying with higher verbosity.
    make
    ('\n    make -j4\n', '\n    make -j$makewidth\n')
    ('\n    make -j4\n', '\n    make -j4\n')
    bash exec (/pybombs/src/apache-thrift):: make -j4
    make: *** No targets specified and no makefile found.  Stop.
    bash return val = 2
    Build failed. See output above for error messages.

Then if we try to get pybombs to install automake:

    root@23ea6420a2cf:/pybombs# ./pybombs install apache-thrift -vvv
    Settled on prefix: 
    Initializing environmental variables...
    ---------- loading recipes -------------------
    Loading recipes ...
    Loading recipes ... done
    ---------- loading recipes finished ----------
    
    Checking if apache-thrift is installed: No
    /
    TMPFILE = /tmpXhoC9V
    WRITE PERMS OK /tmpXhoC9V
    apache-thrift dep [['libtool', 'automake', 'gcc', 'boost', 'bison', 'flex', 'libevent', 'python', 'ssl', 'git']]
    libtool dep [[]]
    automake dep [[]]
    gcc dep [[]]
    boost dep [['python', 'libbzip', 'wget']]
    bison dep [['wget']]
    PyBombs.sysutils - INFO - have_deb: Satisfies requirement...installed version of bison (2.5) is >= than 2.3
    flex dep [['wget']]
    PyBombs.sysutils - INFO - have_deb: Satisfies requirement...installed version of flex (2.5.35) is >= than 2.5.35
    libevent dep [['ssl']]
    python dep [['wget']]
    ssl dep [[]]
    git dep [['wget', 'curl']]
    Installing packages:
    * automake
    * apache-thrift
    install type priority: ['src']
    install src called (automake)
    Installing from source: automake
    [('fetch', <bound method recipe.fetch of <mod_pybombs.recipe.recipe instance at 0x2b3db48>>), ('configure', <bound method recipe.configure of <mod_pybombs.recipe.recipe instance at 0x2b3db48>>), ('make', <bound method recipe.make of <mod_pybombs.recipe.recipe instance at 0x2b3db48>>), ('installed', <bound method recipe.installed of <mod_pybombs.recipe.recipe instance at 0x2b3db48>>)]
    Current step: (automake :: fetch)
    WARNING: no sources available for package automake!
    Traceback (most recent call last):
      File "./pybombs", line 154, in <module>
        pybombs_ops.install(p, not opts.force);
      File "/pybombs/mod_pybombs/pybombs_ops.py", line 115, in install
        global_recipes[pkg].install();
      File "/pybombs/mod_pybombs/recipe.py", line 654, in install
        st = self.install_src();
      File "/pybombs/mod_pybombs/recipe.py", line 728, in install_src
        v.print_v(v.PDEBUG, "setting installed version info (%s,%s)"%(self.last_fetcher.used_source,self.last_fetcher.version))
    AttributeError: recipe instance has no attribute 'last_fetcher'

**Comment by pachulo** [comment]
It's working fine for me. Besides that, Ubuntu 14.04 comes with automake 1.14.1:
http://packages.ubuntu.com/search?keywords=automake&searchon=names&suite=all&section=all
