### ISSUE TITLE
Failed to add new block

### ISSUE THREAD

**Issue by mayankjobanputra** [gnuradio/pybombs#196]
Hi,
Can you please help me? I am facing one problem. I am using the below
version.

mayank@mayank-Vostro-3446:~/gr-howto$ gnuradio-companion --version
GNU Radio Companion 3.7.9git-171-g77083c5d

This program is part of GNU Radio
GRC comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it.

I was adding the very first simple block (given on the gnuradio site)
in that in very first case I didn't got any failed test case.

mayank@mayank-Vostro-3446:~/gr-howto/build$ ctest -V -R square
UpdateCTestConfiguration  from :/home/mayank/gr-howto/build/DartConfiguration.tcl
UpdateCTestConfiguration  from :/home/mayank/gr-howto/build/DartConfiguration.tcl
Test project /home/mayank/gr-howto/build
Constructing a list of tests
Done constructing a list of tests
Checking test dependency graph...
Checking test dependency graph end
test 2
    Start 2: qa_square_ff

2: Test command: /bin/sh "/home/mayank/gr-howto/build/python/qa_square_ff_test.sh"
2: Test timeout computed to be: 9.99988e+06
2: .
2: ----------------------------------------------------------------------
2: Ran 1 test in 0.002s
2: 
2: OK
1/1 Test #2: qa_square_ff .....................   Passed    0.31 sec

The following tests passed:
	qa_square_ff

100% tests passed, 0 tests failed out of 1

Total Test time (real) =   0.31 sec

So I preceded to add xml.
mayank@mayank-Vostro-3446:~/gr-howto$ gr_modtool makexml square_ff

but the error is coming as per follwing:
mayank@mayank-Vostro-3446:~/gr-howto$ gr_modtool makexml square_ff
GNU Radio module name identified: howto
Warning: This is an experimental feature. Don't expect any magic.
Searching for matching files in lib/:
Making GRC bindings for lib/square_ff_impl.cc...
Traceback (most recent call last):
  File "/usr/local/bin/gr_modtool", line 46, in <module>
    main()
  File "/usr/local/bin/gr_modtool", line 38, in main
    modtool.run()
  File
"/usr/local/lib/python2.7/dist-packages/gnuradio/modtool/modtool_makexml.py",
line 75, in run
    (params, iosig, blockname) = self._parse_cc_h(f)
  File
"/usr/local/lib/python2.7/dist-packages/gnuradio/modtool/modtool_makexml.py",
line 174, in _parse_cc_h
    return (parser.read_params(), parser.read_io_signature(), blockname)
  File
"/usr/local/lib/python2.7/dist-packages/gnuradio/modtool/parser_cc_block.py",
line 81, in read_io_signature
    iosig['in'] =
_figure_out_iotype_and_vlen(iosig_match.group('incall'),
AttributeError: 'NoneType' object has no attribute 'group'

Please help me solving this error.

Thanks in advance.

**Comment by osh** [comment]
This has nothing to do with pybombs
