### ISSUE TITLE
Having to call 'ldconfig' after compilation of GNU Radio

### ISSUE THREAD

**Issue by ptrkrysik** [gnuradio/pybombs#199]
Every time I'm installing GNU Radio with pybombs I have to run 

ldconfig 

in order to be able to run GNU Radio applications. 
Shouldn't be ldconfig call added to gnuradio's recipe?

**Comment by mbr0wn** [comment]
This is specific to some platforms, and also, if you don't change the location of .so files, it's usually not necessary.

**Comment by ckuethe** [comment]
It also depends on where and how you're installing gnuradio. If you're installing as non-root, or in a non-standard location, you can use setup_env.sh which will set your LD_LIBRARY_PATH correctly.

**Comment by mbr0wn** [comment]
Let's close this -- it's too specific for something that we can easily fix in PB.
