### ISSUE TITLE
gr-osmosdr enable nonfree for sdrplay

### ISSUE THREAD

**Issue by vsboost** [gnuradio/pybombs#201]
Any way to -DENABLE_NON_FREE=TRUE when gr-osmosdr is being built? i am using an sdrplay and apparently this flag needs to be called for it to work.

Cheers

**Comment by ringof** [comment]
I manually added the line:
 var config_opt = " -DENABLE_NONFREE=TRUE "
in the recipe file gr-osmosdr.lwr in pybombs/recipe/, before the "inherit: cmake" line.

**Comment by vsboost** [comment]
I tried that, still cant pick up the sdrplay in gqrx or gnuradio, any other suggestions.

**Comment by vsboost** [comment]
Ok so my bad, its -DENABLE_NONFREE=TRUE not -DENABLE_NON_FREE=TRUE

All good now

Thanks for that.. :-)

**Comment by wcat13** [comment]
I am trying to rebuild gr-osmosdr with var config_opt = " -DENABLE_NONFREE=TRUE " added just above the "inherit: cmake" line. in ~/wayne/.pybombs/recipes/gr-recipes/gr-osmosdr.lwr

```
pybombs rebuild gr-osmosdr
yaml.scanner.ScannerError: while scanning a simple key
  in "<string>", line 32, column 1:
    var config_opt = " -DENABLE_NONF ... 
    ^
could not found expected ':'
  in "<string>", line 33, column 1:
    inherit: cmake
    ^
```
Hoping one of you can tell me what I am doing wrong?
Regards

**Comment by ringof** [comment]
Just went through this last week. They changed up how the options are
written (booo PyBOMBS docs!). I found this to work:

var: {config_opt: ' -DENABLE_NONFREE=TRUE'}

On Sun, Mar 20, 2016 at 6:54 AM, WCat <notifications@github.com> wrote:

> I am trying to rebuild gr-osmosdr with var config_opt = "
> -DENABLE_NONFREE=TRUE " added just above the "inherit: cmake" line. in
> ~/wayne/.pybombs/recipes/gr-recipes/gr-osmosdr.lwr
>
> pybombs rebuild gr-osmosdr
> yaml.scanner.ScannerError: while scanning a simple key
>   in "<string>", line 32, column 1:
>     var config_opt = " -DENABLE_NONF ...
>     ^
> could not found expected ':'
>   in "<string>", line 33, column 1:
>     inherit: cmake
>     ^
>
> Hoping one of you can tell me what I am doing wrong?
> Regards
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/gnuradio/pybombs/issues/201#issuecomment-198896473>
>



-- 
David Goncalves

**Comment by wcat13** [comment]
Fantastic.

Thank you!

**Comment by mbr0wn** [comment]
PyBOMBS docs need improvement (which happens by providing patches), but I would like point out that all files are in YAML format, which the documentation does emphasize.

**Comment by ringof** [comment]
I am going to find an appropriate home for this tidbit of configuration information.

**Comment by mbr0wn** [comment]
Thanks!
