### ISSUE TITLE
Problem with libboost1.53-dev

### ISSUE THREAD

**Issue by jsa91** [gnuradio/pybombs#209]
When I try to install gr-gsm through pybombs the following problem appears: 

"PyBombs.sysutils - WARNING - deb_exists: could not find a downloadable version of libboost1.53-dev
Installing from source: boost"

The installation gets aborted and fails.
I'm pretty new to Linux and has hoping someone could help me with this.

Thanks!

**Comment by ckuethe** [comment]
You didn't say which distribution or version you're using.

On Wed, Jan 13, 2016 at 2:53 PM, jsa91 <notifications@github.com> wrote:

> When I try to install gr-gsm through pybombs the following problem
> appears:
>
> "PyBombssysutils - WARNING - deb_exists: could not find a downloadable
> version of libboost153-dev
> Installing from source: boost"
>
> The installation gets aborted and fails
> I'm pretty new to Linux and has hoping someone could help me with this
>
> Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gnuradio/pybombs/issues/209>.
>



-- 
GDB has a 'break' feature; why doesn't it have 'fix' too?

**Comment by jsa91** [comment]
Sorry, I'm using Kali Linux 2.0

**Comment by jsa91** [comment]
Pybombs through "git clone" so I assume the latest version. I'm using Kali Linux 2.0.

**Comment by ckuethe** [comment]
OK, I haven't tested with Kali. I'd approach fixing it by looking at what
version of boost development libraries are available in the repositories
and adjusting the deb satisfier to match.

On Wed, Jan 13, 2016 at 3:22 PM, jsa91 <notifications@github.com> wrote:

> Pybombs through "git clone" so I assume the latest version. I'm using Kali
> Linux 2.0.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gnuradio/pybombs/issues/209#issuecomment-171469810>.
>



-- 
GDB has a 'break' feature; why doesn't it have 'fix' too?

**Comment by ckuethe** [comment]
Just tested - PyBOMBS works on a fresh install Kali 2016.01 which provides Boost 1.58. Try updating with "apt-get update && apt-get dist-upgrade" before running PyBOMBS.
