### ISSUE TITLE
Add 'port' package manager

### ISSUE THREAD

**Issue by mbr0wn** [gnuradio/pybombs#232]
<a href="https://github.com/mbr0wn"><img src="https://avatars.githubusercontent.com/u/508035?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mbr0wn](https://github.com/mbr0wn)**
_Wednesday Aug 05, 2015 at 01:22 GMT_
_Originally opened as https://github.com/gnuradio/pybombs2/issues/23_

----

**Comment by sbmueller** [comment]
So I think we're done here as well 👍

**Comment by sdh11** [comment]
Forgot about this. Thanks.
