### ISSUE TITLE
pybombs --version output goes to stderr

### ISSUE THREAD

**Issue by JonZeolla** [gnuradio/pybombs#242]
It appears that pybombs --version output goes to stderr, which causes some confusion when attempting to ensure certain versions of pybombs are in use via scripts.  

sdr@ubuntu:/usr/local$ test=$(pybombs --version)
2.0.0
sdr@ubuntu:/usr/local$ echo $test

sdr@ubuntu:/usr/local$ test=$(pybombs --version 2>&1)
sdr@ubuntu:/usr/local$ echo $test
2.0.0

**Comment by mbr0wn** [comment]
`--version` is handled by ArgParse. Not really much we can do about this.
