### ISSUE TITLE
recipes update fails silently if the local recipe repo has been modified

### ISSUE THREAD

**Issue by miek** [gnuradio/pybombs#259]
Standard run:

    $ pybombs recipes update gr-recipes
    PyBombs.recipes - INFO - Updating recipe location `gr-recipes'...
    Updating: (100%) [================================================================================================================]

With `-vvv`:

    [...]
    PyBombs.Fetcher.git - DEBUG - Using url https://github.com/gnuradio/gr-recipes.git
    PyBombs.Fetcher.git - OBNOXIOUS - Switching cwd to: /home/mike/.pybombs/recipes/gr-recipes
    PyBombs.monitor_process() - DEBUG - Executing command `['git', 'pull', '--rebase']'
    Cannot pull with rebase: You have unstaged changes.
    Please commit or stash them.
    PyBombs.monitor_process() - DEBUG - Thread signaled termination or returned
    PyBombs.monitor_process() - DEBUG - Return value: 1
    PyBombs.Fetcher.git - OBNOXIOUS - Switching cwd back to: /home/mike/.pybombs/recipes

Mostly my own fault for messing with the recipe files, but still would be nice to have a failure message.

**Comment by mbr0wn** [comment]
096e944e9603a536a995153f1e7da4c0928f049e provides a fix. It could be nicer (i.e., it could show the actual error) but for not it's good I think.

Thanks for the comment!
