### ISSUE TITLE
grc path missing from default config

### ISSUE THREAD

**Issue by keesj** [gnuradio/pybombs#266]
While building grc components (like gr_rds) they do not become visible inside gnuradio_companion:

the root cause is that gnuradio_companion's search path does not cover "$prefix//share/gnuradio/grc/blocks"

I found a workaround here by adding that path to the list:
e.g.

```
keesj@keesj-Lenovo-Y50-70:~$ cat .gnuradio/config.conf 
[grc]
global_blocks_path = /home/keesj/projects/sdr/target/share/gnuradio/grc/blocks
```

as documented here:
http://gnuradio.4.n7.nabble.com/PyBOMBS-installed-gnuradio-uhd-usrp-sink-not-found-td48388.html

Is there a way to configure gnuradio-companion to include that path by default?

**Comment by mbr0wn** [comment]
a4e9f930ed3e4a37746dbb9a5fa883469deae4f2 adds this to setup_env.sh, where it should always have been.
