### ISSUE TITLE
pybombs prefix mostly annoying 

### ISSUE THREAD

**Issue by keesj** [gnuradio/pybombs#267]
The pybombs prefix is mostly annoying. The normal use case is for a user to want to install stuff on a single directory (and only sourcing a single env).

It is possible to configure a default prefix (and I did so) in .pybombs/config.yml but this make it hard for first time users to figure out how to do.

```
keesj@keesj-Lenovo-Y50-70:~$ cat .pybombs/config.yml 
config:
  default_prefix: main
```
can pybombs allow one of the following:
option 1:
-Allow to configure a default prefix in the setup_env.sh (e.g. DEFAULT_PREFIX=bla)
option 2:
-Add an option to pybombs prefix init to set the repository as main / default reporitory

**Comment by mbr0wn** [comment]
This is already an option, and is described in the manual.

    $ pybombs config default_prefix <foo>
