### ISSUE TITLE
What is syntax of pybombs 'config' and '--config' parameters

### ISSUE THREAD

**Issue by ptrkrysik** [gnuradio/pybombs#280]
It would be good to have description of how to use 'config' and '--config' parameters.
Lack of documentation decreases usability of these options for new users. Without looking into the code I'm unable to figure out what proper syntax of configuration for these options is.

It would be also good to have example how to use them to disable forced build of gnuradio - as this is probably what most users will use these options for.

**Comment by mbr0wn** [comment]
@ptrkrysik, please either suggest specific changes or even submit a PR here. For discussions, go to the GNU Radio mailing list. I agree it would be great to have many things in PyBOMBS, including better docs (which tool doesn't).

It looks like what you really want is an explanation of the config options themselves, not how to set them. Right? Note we already have an example for `config` in the manual. You could suggest some new ones (as long as it doesn't get bloated).
