### ISSUE TITLE
Syntax error in config leads to incorrect error

### ISSUE THREAD

**Issue by ckuethe** [gnuradio/pybombs#285]
If I use tabs in my config.yml that leads to an error of the form "Package XYZ has no recipe file!"

Possibly the yml parser could be made more tolerant of whitespace errors, or a more clear error message should be printed: "syntax error in $configfile, check whitespace"

**Comment by ckuethe** [comment]
Proposed fix: #295

**Comment by ckuethe** [comment]
Assuming no one has any objections, I plan to merge my patch tomorrow afternoon:  well-formed config files still parse, malformed ones now cause useful error messages to be printed.

**Comment by ckuethe** [comment]
Fixed.

**Comment by mbr0wn** [comment]
Good fix, thanks. But please stick with Python3-compatible code and prefer .format() over %.

**Comment by mbr0wn** [comment]
Also, safe_load can return 'None' without an error. This was formerly caught by the `or {}`. Will need to add that back.

**Comment by ckuethe** [comment]
ACK.
