### ISSUE TITLE
Using python-requests on ftp URLs fails

### ISSUE THREAD

**Issue by marcusmueller** [gnuradio/pybombs#290]
… because requests is an http library. There is a requests-ftp adapter, but I don't think we should be using that. 

There's different possible solutions:

1. Simply find http mirror URLs or git sources for the *three* known recipes that use ftp
 * that might call for the `git.py` fetcher to be aware of tags so PyBOMBS can fetch releases (that'd be a neat feature, anyway); not a great problem, but still.
 * In the long run: deprecate the `wget+http://` schemes; use `http://` (or create an alias); it's not like `requests` is anything but a HTTP handler
2. simply workaround that using urllib for ftp URLs and live without the download progress bar
3. install, and use, `requests-ftp` and let it hotpatch `requests`.
 * Kind of fragile, because no-one knows when that will stop working

**Comment by ckuethe** [comment]
I'll try track down some http urls.


On Fri, Apr 8, 2016 at 10:48 AM, Marcus Müller <notifications@github.com>
wrote:

> … because requests is an http library. There is a requests-ftp adapter,
> but I don't think we should be using that.
>
> There's different possible solutions:
>
>    1. Simply find http mirror URLs or git sources for the *three* known
>    recipes that use ftp
>       - that might call for the git.py fetcher to be aware of tags so
>       PyBOMBS can fetch releases (that'd be a neat feature, anyway); not a great
>       problem, but still.
>       - In the long run: deprecate the wget+http:// schemes; use http://
>       (or create an alias); it's not like requests is anything but a HTTP
>       handler
>    2. simply workaround that using urllib for ftp URLs and live without
>    the download progress bar
>    3. install, and use, requests-ftp and let it hotpatch requests.
>       - Kind of fragile, because no-one knows when that will stop working
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/gnuradio/pybombs/issues/290>
>



-- 
GDB has a 'break' feature; why doesn't it have 'fix' too?

**Comment by marcusmueller** [comment]
Thanks, the problem is especially Alsa; it has plenty of mirrors, but
some aren't really trustworthy or haven't been updated since 1.0.22
(current recipe has 1.0.27, current release is 1.1.1); fedora has a copy
of that on their servers,
http://pkgs.fedoraproject.org/repo/pkgs/alsa-lib/alsa-lib-1.1.1.tar.bz2/881060d2c568f7f49db82c58df2f9ddc/alsa-lib-1.1.1.tar.bz2
but I don't know how long that URL is gonna be around.
I think switching to git for alsa might be worth it.

**Comment by ckuethe** [comment]
https://github.com/gnuradio/gr-recipes/commit/487bdaed1c502b99fced3ec9847c827796722dd4

I went with the tux.org mirror.

**Comment by marcusmueller** [comment]
I'll close this issue then. Unless someone uses an FTP URL in the future, things are solved.

On the other hand, I'm still partial to replacing `wget+http://` with `http://`. What's your opinion on adding that alias?

**Comment by ckuethe** [comment]
Assume an implicit "wget" prefix unless you specify a different fetcher
(like git+ or svn+ or hg+)? Favorable.

On Fri, Apr 8, 2016 at 11:05 AM, Marcus Müller <notifications@github.com>
wrote:

> I'll close this issue then. Unless someone uses an FTP URL in the future,
> things are solved.
>
> On the other hand, I'm still partial to replacing wget+http:// with
> http://. What's your opinion on adding that alias?
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/gnuradio/pybombs/issues/290#issuecomment-207540153>
>



-- 
GDB has a 'break' feature; why doesn't it have 'fix' too?

**Comment by marcusmueller** [comment]
Uh, wait, now I feel stupid; isn't that why
https://github.com/gnuradio/pybombs/blob/master/pybombs/fetchers/base.py
defines `regexes[]`?

Now I'll have to try :)

**Comment by marcusmueller** [comment]
yeah. works.

**Comment by ckuethe** [comment]
Just be careful of github urls and doing the right thing with a repo name (with and without the .git suffix) and a download blob. Not that any recipies are using it right now, but it's worth considering.

**Comment by marcusmueller** [comment]
I just removed all the `wget+`; can't really hurt github URLs that way.

**Comment by mbr0wn** [comment]
DON'T REMOVE THE wget+
