### ISSUE TITLE
"pybombs recipes update" doesnt update all the repos in the default prefix

### ISSUE THREAD

**Issue by ckuethe** [gnuradio/pybombs#291]
pybombs recipe update: error: too few arguments

you can list all the recipes from all the repos in your default prefix, you should be able to update them too.

**Comment by mbr0wn** [comment]
Good idea.

**Comment by mbr0wn** [comment]
You can't actually list recipe locations, though, see #263.

**Comment by mbr0wn** [comment]
9ea9d8c0ab82c7d0c29a0991a283d4193bd7be64
