### ISSUE TITLE
implement a way to regenerate setup_env.sh

### ISSUE THREAD

**Issue by ckuethe** [gnuradio/pybombs#297]
Legacy pybombs used to have the "env" command which would generate some environmental setup shell statements.

- we should probably bring that back for ... unusual ... installation prefixes
- we should mention important path variables in the quickstart for people installing into strange places.

See https://github.com/mossmann/hackrf/issues/248 for more context.

**Comment by mbr0wn** [comment]
`prefix init` does just that.

**Comment by ckuethe** [comment]
I can't run "pybombs prefix init" on an existing prefix. Would it be worth adding an "env" subcommand to rewrite the setup_env.sh file?

**Comment by mbr0wn** [comment]
No, but it would be worth fixing `prefix init` to work on an existing prefix.

**Comment by mbr0wn** [comment]
...or add a command line switch just to write that file for the `prefix` subcommand.

**Comment by ckuethe** [comment]
That's what I meant by subcommand. Something like  "pybombs prefix env" ... which I see is already in use, so "prefix install-env" maybe?

**Comment by mbr0wn** [comment]
OK, that works for me. Do you want to add this?

**Comment by ckuethe** [comment]
I can do it

**Comment by ckuethe** [comment]
PR #300

On Tue, Apr 12, 2016 at 7:21 PM, Chris Kuethe <chris.kuethe@gmail.com>
wrote:

> I can do it
> On Apr 12, 2016 7:19 PM, "mbr0wn" <notifications@github.com> wrote:
>
>> OK, that works for me. Do you want to add this?
>>
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/gnuradio/pybombs/issues/297#issuecomment-209196874>
>>
>


-- 
GDB has a 'break' feature; why doesn't it have 'fix' too?
