### ISSUE TITLE
FTP URI unrecognized

### ISSUE THREAD

**Issue by gr-sp** [gnuradio/pybombs#337]
This may end up being a "won't fix" but I had some trouble with this a few days ago.

Set the source of a recipe to something like:
`source: ftp://ftp.gnu.org/gnu/gcc/gcc-4.8.2/gcc-4.8.2.tar.gz`

Then, `pybombs fetch <pkg>`

Results in:
```
PyBombs.fetch - INFO - Downloading source for package gcc
PyBombs.Fetcher - DEBUG - Fetching source for recipe: gcc
PyBombs.Fetcher - DEBUG - Switching to src directory: /home/shawn/prefixes/myprefix/src
PyBombs.Fetcher - OBNOXIOUS - Trying to fetch ftp://ftp.gnu.org/gnu/gcc/gcc-4.8.2/gcc-4.8.2.tar.gz
PyBombs.Fetcher - DEBUG - That didn't work.
PyBombs.Fetcher - DEBUG - Unrecognized URI: ftp://ftp.gnu.org/gnu/gcc/gcc-4.8.2/gcc-4.8.2.tar.gz
PyBombs.fetch - ERROR - Unable to fetch package gcc. Skipping.
PyBombs.fetch - ERROR - Unable to fetch recipe gcc
```

It doesn't really affect me long term because I found a source that doesn't use the `ftp://` protocol identifier. Sometimes the same resource name (`ftp.gnu.org/gnu/gcc/gcc-4.8.2/gcc-4.8.2.tar.gz`) with a different protocol identifier (e.g. `http://` or `https://`) will work.

The (very) little research I did on this suggests that the requests module is an HTTP library, and thus does not support FTP (see this issue: https://github.com/kennethreitz/requests/issues/1237). However, there is a requests-ftp module (as referenced in the aforementioned issue) but the author warns that this code was put together in a hurry and isn't battle tested (use at your own risk sort of scenario). There is, as another alternative, an ftplib module that comes with python that may do the trick if pybombs wants to support this. I found this link that could be useful in this regard: https://www.atlantic.net/community/howto/ftp-with-python-the-basics/.

I don't know if this is important to anyone (and as I mentioned earlier I found a workaround for my scenario so it doesn't directly impact me) but I just thought I would raise this issue so that it can be formally addressed in case someone else stumbles upon this same problem.

**Comment by mbr0wn** [comment]
Waaah, stop finding bugs! Just kidding. Keep them coming. I just wish there were less of them.

As for this.... we don't have any ftp:// links anywhere right now (neither gr-recipes nor gr-etcetera) so I'll close this for now. Perhaps we should rename the wget fetcher the http fetcher. But that would mean updating all those recipes....
