### ISSUE TITLE
setuptools invalid command name

### ISSUE THREAD

**Issue by gr-sp** [gnuradio/pybombs#338]
I keep having to remove the install_opt var from setuptools.lwt. When building I get:
```
PyBombs._process_thread() - DEBUG - Executing command `python setup.py install --prefix=/home/shawn/prefixes/ta2 setuptools.satisfier==deb?{--install-layout=deb}:{}'
invalid command name 'setuptools.satisfier==deb?{--install-layout=deb}:{}'
```

**Comment by gr-sp** [comment]
OK...so I can't remove it anymore because then $install_opt isn't defined (which is the way it should be). But I can change it from:
```
vars:
        install_opt: "setuptools.satisfier==deb?{--install-layout=deb}:{}"
```
to
```
vars:
        install_opt:
```

**Comment by mbr0wn** [comment]
Yeah that's stupid. PB1 had a magic way of being conditional inside variables. Until we have something like that, it's empty.
