### ISSUE TITLE
[Pybombs Qt GUI frontend] Add QWizardPage for prefix settings

### ISSUE THREAD

**Issue by NinjaComics** [gnuradio/pybombs#345]
Idea is to add a QWizardPage to configure prefix settings, each time Pybombs app store is opened afresh with a "Show at startup" Checkbox. 
If the checkbox is ticked, the user is prompted with a prefix config dialog to either enter a new prefix or choose one of the already existing prefixes. If unchecked, default prefix will be used.
The list of recipes to be displayed on the MainWindow will vary depending upon the prefix selected.

**Comment by NinjaComics** [comment]
This issue can be closed. It is already addressed in [pybombs-gui repo](https://gitlab.com/NinjaComics/pybombs-qtgui)

**Comment by mbr0wn** [comment]
@NinjaComics if you open an issue, you can close it, too.
