### ISSUE TITLE
[Pybombs Qt GUI frontend] Use Whoosh as search backend for the app store

### ISSUE THREAD

**Issue by NinjaComics** [gnuradio/pybombs#347]
[Whoosh](https://whoosh.readthedocs.io/en/latest/index.html) is an indexing and searching library implemented in pure Python. It supports both Python 2.x and 3.x. Instead of natively adding a search and indexing functionality to the pybombs frontend, this library _can_ be used.

**Comment by mbr0wn** [comment]
Make sure not to add a crazy bunch of dependencies. Also, make sure they're installable through pip.
