### ISSUE TITLE
List out info about all the prefixes 

### ISSUE THREAD

**Issue by NinjaComics** [gnuradio/pybombs#348]
For the idea described in #345 (refer screenshot below), it is required to get the list of prefix aliases the user has created earlier. The idea is to add a subcommand listing out info about all the prefixes.     

![prefix_alias](https://cloud.githubusercontent.com/assets/4360717/15771189/ae321f36-2986-11e6-8585-968e200e869b.png)

**Comment by mbr0wn** [comment]
I would suggest a sub-sub-command for `pybombs prefix`.

**Comment by NinjaComics** [comment]
There's already a `pybombs prefix info` which lists out the current prefix directory. I was thinking if we can modify it to list out all the prefix(with aliases) and highlight the active prefix.

**Comment by mbr0wn** [comment]
Yeah that's a good place. `prefix info` is currently not all that useful.

**Comment by mbr0wn** [comment]
22ef131134621e2b936d5f07249b6ef152ebc29f
