### ISSUE TITLE
Jenkins Build

### ISSUE THREAD

**Issue by sgardner340** [gnuradio/pybombs#362]
Hi
I am trying to install pybmbs2 and gnuradio via Jenkins application to perform nighty automated test builds. I am currently receiving the following error.
Finished processing dependencies for PyBOMBS==2.0.1
+ pybombs recipes add gr-recipes git+https://github.com/gnuradio/gr-recipes.git

PyBombs.ConfigManager - INFO - Creating new config file /home/hudson/.pybombs/config.yml 

Cloning: [\ ]
Cloning: [| ]
Cloning: [/ ]
Cloning: [- ]
Cloning: (100%) [=========================================================]
+ pybombs recipes add gr-etcetera git+https://github.com/gnuradio/gr-etcetera.git

Cloning: [\ ]
Cloning: [| ]
Cloning: [/ ]
Cloning: [- ]
Cloning: (100%) [=========================================================]
+ pybombs prefix init /home/hudson/Build_ME -a smokey64 -R gnuradio-default
usage: pybombs [-h] [--version] [-p PREFIX] [--prefix-conf PREFIX_CONF]
[--config CONFIG] [--config-file CONFIG_FILE] [-r RECIPES] [-q]
[-v] [-y]
...
pybombs: error: unrecognized arguments: -R gnuradio-default
Build step 'Execute shell' marked build as failure
[WARNINGS] Skipping publisher since build result is FAILURE
Email was triggered for: Still Failing
Trigger Failure was overridden by another trigger and will not send an email.
Sending email for trigger: Still Failing

**Comment by mbr0wn** [comment]
@sgardner340 Update PyBOMBS to the latest git and you should be fine.
