### ISSUE TITLE
pybombs failing with 16.04 LTS fresh install 

### ISSUE THREAD

**Issue by gwratcliff** [gnuradio/pybombs#366]
Greetings,

Martin you asked that I post a -v result here.  I'm using a recently downloaded and installed, with no other changes Ubuntu build from ground up, nothing else.

Added pybombs with pip.
added recipes per the pybombs instructions.
Executed command: pybombs install gnuradio

Results below
gratcliff@gratcliff-Satellite-L650:~$ pybombs -v install gnuradio
PyBOMBS.ConfigManager - DEBUG - Reading config info from file: /etc/pybombs/config.yml
PyBOMBS.ConfigManager - DEBUG - New config items: {}
PyBOMBS.ConfigManager - DEBUG - Reading config info from file: /home/gratcliff/.pybombs/config.yml
PyBOMBS.ConfigManager - DEBUG - New config items: {'default_prefix': '/home/gratcliff/gnuradio'}
PyBOMBS.ConfigManager - DEBUG - Template directory: /usr/local/lib/python2.7/dist-packages/pybombs/templates
PyBOMBS.ConfigManager.PrefixInfo - DEBUG - Inspecting config file: /etc/pybombs/config.yml
PyBOMBS.ConfigManager.PrefixInfo - DEBUG - Inspecting config file: /home/gratcliff/.pybombs/config.yml
PyBOMBS.ConfigManager.PrefixInfo - DEBUG - Using default_prefix as prefix (/home/gratcliff/gnuradio)
PyBOMBS.ConfigManager.PrefixInfo - DEBUG - Choosing default prefix config dir: /home/gratcliff/gnuradio/.pybombs
PyBOMBS.ConfigManager.PrefixInfo - DEBUG - Config dir does not yet exist.
PyBOMBS.ConfigManager.PrefixInfo - DEBUG - Prefix configuration file not found: /home/gratcliff/gnuradio/.pybombs/config.yml, assuming empty.
PyBOMBS.ConfigManager.PrefixInfo - DEBUG - Prefix source dir is: /home/gratcliff/gnuradio/src
PyBOMBS.ConfigManager.PrefixInfo - DEBUG - Prefix inventory file not found: /home/gratcliff/gnuradio/.pybombs/inventory.yml
PyBOMBS.Inventory - DEBUG - Trying to load inventory file /home/gratcliff/gnuradio/.pybombs/inventory.yml...
PyBOMBS.ConfigManager - DEBUG - Full list of recipe locations: ['/home/gratcliff/.pybombs/recipes/gr-etcetera', '/home/gratcliff/.pybombs/recipes/gr-recipes', '/usr/local/lib/python2.7/dist-packages/pybombs/recipes']
PyBOMBS.ConfigManager - DEBUG - Named recipe locations: {'gr-etcetera': 'git+https://github.com/gnuradio/gr-etcetera.git', 'gr-recipes': 'git+https://github.com/gnuradio/gr-recipes.git'}
PyBOMBS - INFO - PyBOMBS Version 2.1.0
PyBOMBS.RecipeListManager - DEBUG - Adding recipe location: /home/gratcliff/.pybombs/recipes/gr-etcetera
PyBOMBS.RecipeListManager - DEBUG - Scanning directory '/home/gratcliff/.pybombs/recipes/gr-etcetera' for recipes...
PyBOMBS.RecipeListManager - DEBUG - Found 51 new recipes.
PyBOMBS.RecipeListManager - DEBUG - Loading templates.
PyBOMBS.RecipeListManager - DEBUG - Adding recipe location: /home/gratcliff/.pybombs/recipes/gr-recipes
PyBOMBS.RecipeListManager - DEBUG - Scanning directory '/home/gratcliff/.pybombs/recipes/gr-recipes' for recipes...
PyBOMBS.RecipeListManager - DEBUG - Found 165 new recipes.
PyBOMBS.RecipeListManager - DEBUG - Loading templates.
PyBOMBS.RecipeListManager - DEBUG - Adding recipe location: /usr/local/lib/python2.7/dist-packages/pybombs/recipes
PyBOMBS.RecipeListManager - DEBUG - Scanning directory '/usr/local/lib/python2.7/dist-packages/pybombs/recipes' for recipes...
PyBOMBS.RecipeListManager - DEBUG - Found 11 new recipes.
PyBOMBS.RecipeListManager - DEBUG - Loading templates.
PyBOMBS.install - DEBUG - Initializing command class for command install
PyBOMBS.PackageManager - DEBUG - Attempting to add binary package manager pip
PyBOMBS.PackageManager - DEBUG - pip is supported!
PyBOMBS.PackageManager - DEBUG - Attempting to add binary package manager apt-get
PyBOMBS.PackageManager - DEBUG - apt-get is supported!
PyBOMBS.PackageManager - DEBUG - Attempting to add binary package manager yumdnf
PyBOMBS.PackageManager - DEBUG - Attempting to add binary package manager port
PyBOMBS.PackageManager - DEBUG - Attempting to add binary package manager brew
PyBOMBS.PackageManager - DEBUG - Attempting to add binary package manager pacman
PyBOMBS.PackageManager - DEBUG - Attempting to add binary package manager portage
PyBOMBS.PackageManager - DEBUG - Attempting to add binary package manager pkgconfig
PyBOMBS.PackageManager - DEBUG - pkgconfig is supported!
PyBOMBS.PackageManager - DEBUG - Attempting to add binary package manager cmd
PyBOMBS.PackageManager - DEBUG - cmd is supported!
PyBOMBS.PackageManager - DEBUG - Using packagers: ['pip', 'apt-get', 'pkgconfig', 'cmd', 'source']
PyBOMBS.PackageManager - DEBUG - Attempting to add binary package manager pip
PyBOMBS.PackageManager - DEBUG - pip is supported!
PyBOMBS.PackageManager - DEBUG - Attempting to add binary package manager apt-get
PyBOMBS.PackageManager - DEBUG - apt-get is supported!
PyBOMBS.PackageManager - DEBUG - Attempting to add binary package manager yumdnf
PyBOMBS.PackageManager - DEBUG - Attempting to add binary package manager port
PyBOMBS.PackageManager - DEBUG - Attempting to add binary package manager brew
PyBOMBS.PackageManager - DEBUG - Attempting to add binary package manager pacman
PyBOMBS.PackageManager - DEBUG - Attempting to add binary package manager portage
PyBOMBS.PackageManager - DEBUG - Attempting to add binary package manager pkgconfig
PyBOMBS.PackageManager - DEBUG - pkgconfig is supported!
PyBOMBS.PackageManager - DEBUG - Attempting to add binary package manager cmd
PyBOMBS.PackageManager - DEBUG - cmd is supported!
PyBOMBS.PackageManager - DEBUG - Using packagers: ['pip', 'apt-get', 'pkgconfig', 'cmd', 'source']
PyBOMBS.PackageManager - DEBUG - Checking if package gnuradio is installed.
PyBOMBS.PackageManager - DEBUG - Package gnuradio is requesting a source build.
PyBOMBS.PackageManager - DEBUG - Checking if package gnuradio is installed.
PyBOMBS.PackageManager - DEBUG - Package gnuradio is requesting a source build.
PyBOMBS.PackageManager - DEBUG - Checking if package gnuradio is installed.
PyBOMBS.PackageManager - DEBUG - Package gnuradio is requesting a source build.
PyBOMBS.PackageManager - DEBUG - Checking if package gnuradio is installable.
PyBOMBS.PackageManager - DEBUG - Package gnuradio is requesting a source build.
PyBOMBS.PackageManager - DEBUG - Checking if package boost is installed.
PyBOMBS.Packager.apt-get - DEBUG - Package libboost-all-dev has version 1.58.0 in dpkg
PyBOMBS.PackageManager - DEBUG - Checking if package fftw is installed.
PyBOMBS.PackageManager - DEBUG - Checking if package cppunit is installed.
PyBOMBS.Packager.apt-get - DEBUG - Package libcppunit-dev has version 1.13.2 in dpkg
PyBOMBS.PackageManager - DEBUG - Checking if package swig is installed.
PyBOMBS.Packager.apt-get - DEBUG - Package swig2.0 has version 2.0.12 in dpkg
PyBOMBS.PackageManager - DEBUG - Checking if package gsl is installed.
PyBOMBS.Packager.apt-get - DEBUG - Package libgsl-dev has version 2.1 in dpkg
PyBOMBS.PackageManager - DEBUG - Checking if package uhd is installed.
PyBOMBS.PackageManager - DEBUG - Checking if package alsa is installed.
PyBOMBS.Packager.apt-get - DEBUG - Package libasound2-dev has version 1.1.0 in dpkg
PyBOMBS.PackageManager - DEBUG - Checking if package cheetah is installed.
PyBOMBS.PackageManager - DEBUG - Checking if package wxpython is installed.
PyBOMBS.PackageManager - DEBUG - Checking if package numpy is installed.
PyBOMBS.Packager.apt-get - DEBUG - Package python-numpy has version 1.11.0 in dpkg
PyBOMBS.PackageManager - DEBUG - Checking if package lxml is installed.
PyBOMBS.PackageManager - DEBUG - Checking if package pygtk is installed.
PyBOMBS.PackageManager - DEBUG - Checking if package pycairo is installed.
PyBOMBS.PackageManager - DEBUG - Checking if package cmake is installed.
PyBOMBS.Packager.apt-get - DEBUG - Package cmake has version 3.5.1 in dpkg
PyBOMBS.Packager.apt-get - DEBUG - Package cmake-data has version 3.5.1 in dpkg
PyBOMBS.PackageManager - DEBUG - Checking if package pyqt4 is installed.
PyBOMBS.Packager.apt-get - DEBUG - Package python-qt4 has version 4.11.4 in dpkg
PyBOMBS.Packager.apt-get - DEBUG - Package pyqt4-dev-tools has version 4.11.4 in dpkg
PyBOMBS.PackageManager - DEBUG - Checking if package pyqwt5 is installed.
PyBOMBS.Packager.apt-get - DEBUG - Package python-qwt5-qt4 has version 5.2.1 in dpkg
PyBOMBS.PackageManager - DEBUG - Checking if package apache-thrift is installed.
PyBOMBS.PackageManager - DEBUG - Checking if package liblog4cpp is installed.
PyBOMBS.PackageManager - DEBUG - Checking if package zeromq is installed.
PyBOMBS.Packager.apt-get - DEBUG - Package libzmq3-dev has version 4.1.4 in dpkg
PyBOMBS.PackageManager - DEBUG - Checking if package uhd is installed.
PyBOMBS.PackageManager - DEBUG - Checking if package uhd is installable.
PyBOMBS.Packager.apt-get - DEBUG - Package uhd-host has version 3.9.2 in apt-cache
PyBOMBS.Packager.apt-get - DEBUG - Package libuhd-dev has version 3.9.2 in apt-cache
PyBOMBS.PackageManager - DEBUG - Checking if package python-requests is installed.
PyBOMBS.Packager.pip - DEBUG - Loading pip install cache.
PyBOMBS.PackageManager - DEBUG - Checking if package libusb is installed.
PyBOMBS.PackageManager - DEBUG - Checking if package doxygen is installed.
PyBOMBS.PackageManager - DEBUG - Checking if package mako is installed.
PyBOMBS.PackageManager - DEBUG - Checking if package mako is installed.
PyBOMBS.PackageManager - DEBUG - Checking if package mako is installable.
PyBOMBS.PackageManager - DEBUG - Checking if package python is installed.
PyBOMBS.Packager.apt-get - DEBUG - Package python2.7 has version 2.7.11 in dpkg
PyBOMBS.Packager.apt-get - DEBUG - Package python-dev has version 2.7.11 in dpkg
PyBOMBS.PackageManager - DEBUG - Checking if package libusb is installed.
PyBOMBS.PackageManager - DEBUG - Checking if package libusb is installable.
PyBOMBS.Packager.apt-get - DEBUG - Package libusb-1.0-0-dev has version 1.0.20 in apt-cache
PyBOMBS.PackageManager - DEBUG - Checking if package autoconf is installed.
PyBOMBS.Packager.apt-get - DEBUG - Package autoconf has version 2.69 in dpkg
PyBOMBS.PackageManager - DEBUG - Checking if package automake is installed.
PyBOMBS.Packager.apt-get - DEBUG - Package automake has version 1.15 in dpkg
PyBOMBS.PackageManager - DEBUG - Checking if package doxygen is installed.
PyBOMBS.PackageManager - DEBUG - Checking if package doxygen is installable.
PyBOMBS.Packager.apt-get - DEBUG - Package doxygen has version 1.8.11 in apt-cache
PyBOMBS.PackageManager - DEBUG - Checking if package lxml is installed.
PyBOMBS.PackageManager - DEBUG - Checking if package lxml is installable.
PyBOMBS.Packager.apt-get - DEBUG - Package python-lxml has version 3.5.0 in apt-cache
PyBOMBS.PackageManager - DEBUG - Checking if package libxml is installed.
PyBOMBS.PackageManager - DEBUG - Checking if package libxslt is installed.
PyBOMBS.PackageManager - DEBUG - Checking if package setuptools is installed.
PyBOMBS.Packager.apt-get - DEBUG - Package python-setuptools has version 20.7.0 in dpkg
PyBOMBS.PackageManager - DEBUG - Checking if package libxslt is installed.
PyBOMBS.PackageManager - DEBUG - Checking if package libxslt is installable.
PyBOMBS.Packager.apt-get - DEBUG - Package libxslt1-dev has version 1.1.28 in apt-cache
PyBOMBS.PackageManager - DEBUG - Checking if package libxml is installed.
PyBOMBS.PackageManager - DEBUG - Checking if package libxml is installable.
PyBOMBS.Packager.apt-get - DEBUG - Package libxml2-dev has version 2.9.3 in apt-cache
PyBOMBS.PackageManager - DEBUG - Checking if package pycairo is installed.
PyBOMBS.PackageManager - DEBUG - Checking if package pycairo is installable.
PyBOMBS.Packager.apt-get - DEBUG - Package python-cairo-dev has version 1.8.8 in apt-cache
PyBOMBS.PackageManager - DEBUG - Checking if package cairo is installed.
PyBOMBS.Packager.apt-get - DEBUG - Package libcairo2 has version 1.14.6 in dpkg
PyBOMBS.PackageManager - DEBUG - Checking if package fftw is installed.
PyBOMBS.PackageManager - DEBUG - Checking if package fftw is installable.
PyBOMBS.Packager.apt-get - DEBUG - Package libfftw3-3 has version 3.3.4 in apt-cache
PyBOMBS.Packager.apt-get - DEBUG - Package libfftw3-dev has version 3.3.4 in apt-cache
PyBOMBS.PackageManager - DEBUG - Checking if package pygtk is installed.
PyBOMBS.PackageManager - DEBUG - Checking if package pygtk is installable.
PyBOMBS.Packager.apt-get - DEBUG - Package python-gtk2 has version 2.24.0 in apt-cache
PyBOMBS.PackageManager - DEBUG - Checking if package gtk2 is installed.
PyBOMBS.PackageManager - DEBUG - Checking if package pygobject is installed.
PyBOMBS.PackageManager - DEBUG - Checking if package pango is installed.
PyBOMBS.Packager.apt-get - DEBUG - Package libpango1.0-0 has version 1.38.1 in dpkg
PyBOMBS.PackageManager - DEBUG - Checking if package pygobject is installed.
PyBOMBS.PackageManager - DEBUG - Checking if package pygobject is installable.
PyBOMBS.Packager.apt-get - DEBUG - Package python-gobject-dev has version 3.20.0 in apt-cache
PyBOMBS.PackageManager - DEBUG - Checking if package gobject-introspection is installed.
PyBOMBS.PackageManager - DEBUG - Checking if package gtk2 is installed.
PyBOMBS.PackageManager - DEBUG - Checking if package gobject-introspection is installed.
PyBOMBS.PackageManager - DEBUG - Checking if package gobject-introspection is installable.
PyBOMBS.Packager.apt-get - DEBUG - Package gobject-introspection has version 1.46.0 in apt-cache
PyBOMBS.PackageManager - DEBUG - Checking if package ffi is installed.
PyBOMBS.Packager.apt-get - DEBUG - Package libffi6 has version 3.2.1 in dpkg
PyBOMBS.PackageManager - DEBUG - Checking if package gtk2 is installed.
PyBOMBS.PackageManager - DEBUG - Checking if package pycairo is installed.
PyBOMBS.PackageManager - DEBUG - Checking if package flex is installed.
PyBOMBS.Packager.apt-get - DEBUG - Package flex has version 2.6.0 in dpkg
PyBOMBS.PackageManager - DEBUG - Checking if package bison is installed.
PyBOMBS.Packager.apt-get - DEBUG - Package bison has version 3.0.4 in dpkg
PyBOMBS.PackageManager - DEBUG - Checking if package pycairo is installed.
PyBOMBS.PackageManager - DEBUG - Checking if package gtk2 is installed.
PyBOMBS.PackageManager - DEBUG - Checking if package gtk2 is installable.
PyBOMBS.Packager.apt-get - DEBUG - Package libgtk2.0-dev has version 2.24.30 in apt-cache
PyBOMBS.PackageManager - DEBUG - Checking if package glib is installed.
PyBOMBS.PackageManager - DEBUG - Checking if package gdk-pixbuf is installed.
PyBOMBS.PackageManager - DEBUG - Checking if package atk is installed.
PyBOMBS.Packager.apt-get - DEBUG - Package libatk1.0-0 has version 2.18.0 in dpkg
PyBOMBS.PackageManager - DEBUG - Checking if package libtiff is installed.
PyBOMBS.PackageManager - DEBUG - Checking if package libjpeg is installed.
PyBOMBS.PackageManager - DEBUG - Checking if package glib is installed.
PyBOMBS.PackageManager - DEBUG - Checking if package glib is installable.
PyBOMBS.Packager.apt-get - DEBUG - Package libglib2.0-dev has version 2.48.1 in apt-cache
PyBOMBS.PackageManager - DEBUG - Checking if package gdk-pixbuf is installed.
PyBOMBS.PackageManager - DEBUG - Checking if package gdk-pixbuf is installable.
PyBOMBS.Packager.apt-get - DEBUG - Package libgdk-pixbuf2.0-dev has version 2.32.2 in apt-cache
PyBOMBS.PackageManager - DEBUG - Checking if package wget is installed.
PyBOMBS.Packager.apt-get - DEBUG - Package wget has version 1.17.1 in dpkg
PyBOMBS.PackageManager - DEBUG - Checking if package libtiff is installed.
PyBOMBS.PackageManager - DEBUG - Checking if package libpng is installed.
PyBOMBS.PackageManager - DEBUG - Checking if package libjpeg is installed.
PyBOMBS.PackageManager - DEBUG - Checking if package glib is installed.
PyBOMBS.PackageManager - DEBUG - Checking if package libpng is installed.
PyBOMBS.PackageManager - DEBUG - Checking if package libpng is installable.
PyBOMBS.Packager.apt-get - DEBUG - Package libpng12-dev has version 1.2.54 in apt-cache
PyBOMBS.PackageManager - DEBUG - Checking if package libjpeg is installed.
PyBOMBS.PackageManager - DEBUG - Checking if package libtiff is installed.
PyBOMBS.PackageManager - DEBUG - Checking if package glib is installed.
PyBOMBS.PackageManager - DEBUG - Checking if package libtiff is installed.
PyBOMBS.PackageManager - DEBUG - Checking if package libjpeg is installed.
PyBOMBS.PackageManager - DEBUG - Checking if package gtk2 is installed.
PyBOMBS.PackageManager - DEBUG - Checking if package glib is installed.
PyBOMBS.PackageManager - DEBUG - Checking if package gdk-pixbuf is installed.
PyBOMBS.PackageManager - DEBUG - Checking if package libtiff is installed.
PyBOMBS.PackageManager - DEBUG - Checking if package libjpeg is installed.
PyBOMBS.PackageManager - DEBUG - Checking if package glib is installed.
PyBOMBS.PackageManager - DEBUG - Checking if package gdk-pixbuf is installed.
PyBOMBS.PackageManager - DEBUG - Checking if package libtiff is installed.
PyBOMBS.PackageManager - DEBUG - Checking if package libpng is installed.
PyBOMBS.PackageManager - DEBUG - Checking if package libjpeg is installed.
PyBOMBS.PackageManager - DEBUG - Checking if package glib is installed.
PyBOMBS.PackageManager - DEBUG - Checking if package libpng is installed.
PyBOMBS.PackageManager - DEBUG - Checking if package libjpeg is installed.
PyBOMBS.PackageManager - DEBUG - Checking if package libtiff is installed.
PyBOMBS.PackageManager - DEBUG - Checking if package glib is installed.
PyBOMBS.PackageManager - DEBUG - Checking if package libtiff is installed.
PyBOMBS.PackageManager - DEBUG - Checking if package libjpeg is installed.
PyBOMBS.PackageManager - DEBUG - Checking if package gtk2 is installed.
PyBOMBS.PackageManager - DEBUG - Checking if package glib is installed.
PyBOMBS.PackageManager - DEBUG - Checking if package gdk-pixbuf is installed.
PyBOMBS.PackageManager - DEBUG - Checking if package libtiff is installed.
PyBOMBS.PackageManager - DEBUG - Checking if package libjpeg is installed.
PyBOMBS.PackageManager - DEBUG - Checking if package glib is installed.
PyBOMBS.PackageManager - DEBUG - Checking if package gdk-pixbuf is installed.
PyBOMBS.PackageManager - DEBUG - Checking if package libtiff is installed.
PyBOMBS.PackageManager - DEBUG - Checking if package libpng is installed.
PyBOMBS.PackageManager - DEBUG - Checking if package libjpeg is installed.
PyBOMBS.PackageManager - DEBUG - Checking if package glib is installed.
PyBOMBS.PackageManager - DEBUG - Checking if package libpng is installed.
PyBOMBS.PackageManager - DEBUG - Checking if package libjpeg is installed.
PyBOMBS.PackageManager - DEBUG - Checking if package libtiff is installed.
PyBOMBS.PackageManager - DEBUG - Checking if package glib is installed.
PyBOMBS.PackageManager - DEBUG - Checking if package libtiff is installed.
PyBOMBS.PackageManager - DEBUG - Checking if package libjpeg is installed.
PyBOMBS.PackageManager - DEBUG - Checking if package wxpython is installed.
PyBOMBS.PackageManager - DEBUG - Checking if package wxpython is installable.
PyBOMBS.Packager.apt-get - DEBUG - Package python-wxgtk3.0 has version 3.0.2 in apt-cache
PyBOMBS.PackageManager - DEBUG - Checking if package gtk2 is installed.
PyBOMBS.PackageManager - DEBUG - Checking if package gtk2 is installed.
PyBOMBS.PackageManager - DEBUG - Checking if package glib is installed.
PyBOMBS.PackageManager - DEBUG - Checking if package gdk-pixbuf is installed.
PyBOMBS.PackageManager - DEBUG - Checking if package libtiff is installed.
PyBOMBS.PackageManager - DEBUG - Checking if package libjpeg is installed.
PyBOMBS.PackageManager - DEBUG - Checking if package glib is installed.
PyBOMBS.PackageManager - DEBUG - Checking if package gdk-pixbuf is installed.
PyBOMBS.PackageManager - DEBUG - Checking if package libtiff is installed.
PyBOMBS.PackageManager - DEBUG - Checking if package libpng is installed.
PyBOMBS.PackageManager - DEBUG - Checking if package libjpeg is installed.
PyBOMBS.PackageManager - DEBUG - Checking if package glib is installed.
PyBOMBS.PackageManager - DEBUG - Checking if package libpng is installed.
PyBOMBS.PackageManager - DEBUG - Checking if package libjpeg is installed.
PyBOMBS.PackageManager - DEBUG - Checking if package libtiff is installed.
PyBOMBS.PackageManager - DEBUG - Checking if package glib is installed.
PyBOMBS.PackageManager - DEBUG - Checking if package libtiff is installed.
PyBOMBS.PackageManager - DEBUG - Checking if package libjpeg is installed.
PyBOMBS.PackageManager - DEBUG - Checking if package liblog4cpp is installed.
PyBOMBS.PackageManager - DEBUG - Checking if package liblog4cpp is installable.
PyBOMBS.Packager.apt-get - DEBUG - Package liblog4cpp5-dev has version 1.0 in apt-cache
PyBOMBS.PackageManager - DEBUG - Checking if package libtool is installed.
PyBOMBS.Packager.apt-get - DEBUG - Package libtool has version 2.4.6 in dpkg
PyBOMBS.PackageManager - DEBUG - Checking if package gcc is installed.
PyBOMBS.Packager.apt-get - DEBUG - No satisfy rule for package type deb
PyBOMBS.Packager.cmd - DEBUG - Found version number: 5.3.1
PyBOMBS.PackageManager - DEBUG - Checking if package cheetah is installed.
PyBOMBS.PackageManager - DEBUG - Checking if package cheetah is installable.
PyBOMBS.Packager.apt-get - DEBUG - Package python-cheetah has version 2.4.4 in apt-cache
PyBOMBS.PackageManager - DEBUG - Checking if package apache-thrift is installed.
PyBOMBS.PackageManager - DEBUG - Checking if package apache-thrift is installable.
PyBOMBS.PackageManager - DEBUG - Checking if package libevent is installed.
PyBOMBS.Packager.apt-get - DEBUG - Package libevent-dev has version 2.0.21 in dpkg
PyBOMBS.PackageManager - DEBUG - Checking if package ssl is installed.
PyBOMBS.Packager.apt-get - DEBUG - Package libssl-dev has version 1.0.2 in dpkg
PyBOMBS.PackageManager - DEBUG - Checking if package pkg-config is installed.
PyBOMBS.Packager.apt-get - DEBUG - Package pkg-config has version 0.29.1 in dpkg
PyBOMBS.PackageManager - DEBUG - Checking if package twisted is installed.
PyBOMBS.Packager.apt-get - DEBUG - Package python-twisted has version 16.0.0 in dpkg
Install tree:
|
\- gnuradio
   |
   +- uhd
   |  |
   |  +- mako
   |  |
   |  +- libusb
   |  |
   |  \- doxygen
   |
   +- lxml
   |  |
   |  +- libxslt
   |  |
   |  \- libxml
   |
   +- pycairo
   |
   +- fftw
   |
   +- pygtk
   |  |
   |  +- pygobject
   |  |  |
   |  |  +- gobject-introspection
   |  |  |  |
   |  |  |  +- pycairo
   |  |  |  |
   |  |  |  \- gtk2
   |  |  |     |
   |  |  |     +- glib
   |  |  |     |
   |  |  |     +- gdk-pixbuf
   |  |  |     |  |
   |  |  |     |  +- libpng
   |  |  |     |  |
   |  |  |     |  +- libjpeg
   |  |  |     |  |
   |  |  |     |  +- libtiff
   |  |  |     |  |
   |  |  |     |  \- glib
   |  |  |     |
   |  |  |     +- libtiff
   |  |  |     |
   |  |  |     \- libjpeg
   |  |  |
   |  |  \- gtk2
   |  |     |
   |  |     +- glib
   |  |     |
   |  |     +- gdk-pixbuf
   |  |     |  |
   |  |     |  +- libpng
   |  |     |  |
   |  |     |  +- libjpeg
   |  |     |  |
   |  |     |  +- libtiff
   |  |     |  |
   |  |     |  \- glib
   |  |     |
   |  |     +- libtiff
   |  |     |
   |  |     \- libjpeg
   |  |
   |  \- gtk2
   |     |
   |     +- glib
   |     |
   |     +- gdk-pixbuf
   |     |  |
   |     |  +- libpng
   |     |  |
   |     |  +- libjpeg
   |     |  |
   |     |  +- libtiff
   |     |  |
   |     |  \- glib
   |     |
   |     +- libtiff
   |     |
   |     \- libjpeg
   |
   +- wxpython
   |  |
   |  \- gtk2
   |     |
   |     +- glib
   |     |
   |     +- gdk-pixbuf
   |     |  |
   |     |  +- libpng
   |     |  |
   |     |  +- libjpeg
   |     |  |
   |     |  +- libtiff
   |     |  |
   |     |  \- glib
   |     |
   |     +- libtiff
   |     |
   |     \- libjpeg
   |
   +- liblog4cpp
   |
   +- cheetah
   |
   \- apache-thrift
PyBOMBS.PackageManager - DEBUG - Checking if package apache-thrift is installed.
PyBOMBS.install_manager - INFO - Installing package: apache-thrift
PyBOMBS.PackageManager - DEBUG - install(apache-thrift, static=False)
PyBOMBS.PackageManager - DEBUG - Using packager pip
PyBOMBS.PackageManager - DEBUG - Using packager apt-get
PyBOMBS.PackageManager - DEBUG - Using packager pkgconfig
PyBOMBS.PackageManager - DEBUG - Using packager cmd
PyBOMBS.PackageManager - DEBUG - Using packager source
PyBOMBS.Packager.source - DEBUG - State on package apache-thrift is 0
PyBOMBS.Fetcher - DEBUG - Fetching source for recipe: apache-thrift
PyBOMBS.Fetcher - INFO - Already fetched: apache-thrift
PyBOMBS.Packager.source - DEBUG - Using build directory: /home/gratcliff/gnuradio/src/apache-thrift
PyBOMBS.Packager.source - DEBUG - Configuring recipe apache-thrift
PyBOMBS.Packager.source - DEBUG - Using vars - {'config_opt': '', 'builddir': '/home/gratcliff/gnuradio/src/apache-thrift'}
PyBOMBS.Packager.source - DEBUG - In cwd - /home/gratcliff/gnuradio/src/apache-thrift
PyBOMBS._process_thread() - DEBUG - Executing command `./bootstrap.sh && ./configure --prefix=/home/gratcliff/gnuradio --with-c_glib --with-cpp --with-libevent --with-python --without-csharp --without-d --without-erlang --without-go --without-haskell --without-java --without-lua --without-nodejs --without-perl --without-php --without-ruby --without-zlib --without-qt4 --without-qt5 --disable-tests --disable-tutorial  CC= CXX= PY_PREFIX=/home/gratcliff/gnuradio CXXFLAGS="-DNDEBUG"'
Configuring: (100%) [=========================================================]
PyBOMBS.monitor_process() - DEBUG - Thread signaled termination or returned
PyBOMBS.monitor_process() - DEBUG - Return value: 0
PyBOMBS.Packager.source - DEBUG - Configure successful.
PyBOMBS.Inventory - DEBUG - Setting state to `configured'
Traceback (most recent call last):
  File "/usr/local/bin/pybombs", line 9, in <module>
    load_entry_point('PyBOMBS==2.1.0', 'console_scripts', 'pybombs')()
  File "/usr/local/lib/python2.7/dist-packages/pybombs/main.py", line 32, in main
    return dispatch() or 0
  File "/usr/local/lib/python2.7/dist-packages/pybombs/commands/base.py", line 187, in dispatch
    return get_cmd_dict(cmd_list)[args.command](cmd=args.command, args=args).run()
  File "/usr/local/lib/python2.7/dist-packages/pybombs/commands/install.py", line 122, in run
    static=getattr(self.args, 'static', False),
  File "/usr/local/lib/python2.7/dist-packages/pybombs/install_manager.py", line 85, in install
    if not self.pm.install(pkg, static=static, verify=verify):
  File "/usr/local/lib/python2.7/dist-packages/pybombs/package_manager.py", line 198, in install
    static=static,
  File "/usr/local/lib/python2.7/dist-packages/pybombs/package_manager.py", line 235, in _std_package_operation
    result = getattr(pkgr, operation)(rec, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pybombs/packagers/source.py", line 110, in install
    fail_if_builddir_missing=update,
  File "/usr/local/lib/python2.7/dist-packages/pybombs/packagers/source.py", line 240, in run_build
    set_state(self.inventory.STATE_CONFIGURED)
  File "/usr/local/lib/python2.7/dist-packages/pybombs/packagers/source.py", line 208, in <lambda>
    set_state = lambda state: self.inventory.set_state(recipe.id, state) or self.inventory.save()
  File "/usr/local/lib/python2.7/dist-packages/pybombs/inventory.py", line 126, in set_state
    self._invfile.update({pkg: {'state': state}})
  File "/usr/local/lib/python2.7/dist-packages/pybombs/config_file.py", line 57, in update
    self.save()
  File "/usr/local/lib/python2.7/dist-packages/pybombs/config_file.py", line 52, in save
    open(self._filename, 'w').write(yaml.dump(self.data, default_flow_style=False))
IOError: [Errno 2] No such file or directory: '/home/gratcliff/gnuradio/.pybombs/inventory.yml'
gratcliff@gratcliff-Satellite-L650:~$

**Comment by mbr0wn** [comment]
@gwratcliff Thanks a lot, very helpful, much appreciated. I think I know what's up -- if you create the directory `/home/gratcliff/gnuradio/.pybombs/` you'll probably be fine. But I'll have a fix up for this soon.

**Comment by mbr0wn** [comment]
@gwratcliff Could it be that you're not creating your prefix with `pybombs prefix init`?

**Comment by mbr0wn** [comment]
FYI, this line tipped me off:
```
 PyBOMBS.ConfigManager.PrefixInfo - DEBUG - Config dir does not yet exist.
```

**Comment by mbr0wn** [comment]
Not sure if this is still an issue....

**Comment by mbr0wn** [comment]
Closing -- not sure if still an issue.
