### ISSUE TITLE
clean up failed install of prefix recipe (prefix init)

### ISSUE THREAD

**Issue by noc0lour** [gnuradio/pybombs#380]
If `pybombs prefix ~pybombs -a myprefix -R gnuradio-default` fails there should be a way to recover from it. A user shouldn't be required to wipe successful installations made up this point. Continuation with `pybombs prefix init` or maybe `pybombs -p myprefix gnuradio-default` should be possible.

**Comment by mbr0wn** [comment]
f00413b625644258c7bf7214a2faae85f47e58e3
