### ISSUE TITLE
Error for Missing Dependency

### ISSUE THREAD

**Issue by mackmgg** [gnuradio/pybombs#384]
When an installation fails due to a missing dependency, the error message is a DEBUG message, so nothing is shown if `-v` is not selected:

`PyBOMBS - DEBUG - Package does not exist: ssl (declared as dependency for package lib event)`

It seems to me that using ERROR instead of DEBUG for a fatal error would make more sense.

**Comment by mbr0wn** [comment]
Yup. Lemme fix.
