### ISSUE TITLE
tokenizer problem with library versions containing '+'

### ISSUE THREAD

**Issue by ckuethe** [gnuradio/pybombs#388]
See #387

    $ pybombs lint db48.lwr 
    PyBOMBS - INFO - PyBOMBS Version 2.1.1a
    Linting recipe `db48.lwr'
    [VERY BAD] - Recipe error: Invalid token: +
    [HMM] Recipe doesn't have key: depends

**Comment by mbr0wn** [comment]
Is this fixed with your PR? @ckuethe

**Comment by ckuethe** [comment]
No, this just allows pybombs to not crash when parsing the file. I still have to figure out how to fix the parsing of files with `+` in their paths.

**Comment by mbr0wn** [comment]
f485ec0cb34403ce30074baa4a2afb8b77235554 should take care of this.
