### ISSUE TITLE
- ERROR - Error installing package ssl. Aborting

### ISSUE THREAD

**Issue by stackprogramer** [gnuradio/pybombs#392]
when i want to install gnuradio with pybombs ,in command:
$ pybombs prefix init /path/to/prefix -a myprefix -R gnuradio-default
it returna errors:

> eb8u2
>   404  Not Found
> Err http://debian.csail.mit.edu/debian/ jessie/main libssl-doc all 1.0.1t-1+deb8u2
>   404  Not Found
> E: Failed to fetch http://debian.csail.mit.edu/debian/pool/main/o/openssl/libssl-dev_1.0.1t-1+deb8u2_amd64.deb  404  Not Found
> 
> E: Failed to fetch http://debian.csail.mit.edu/debian/pool/main/o/openssl/libssl-doc_1.0.1t-1+deb8u2_all.deb  404  Not Found
> 
> E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
> PyBOMBS.PackageManager - ERROR - Something went wrong while trying to install ssl using apt-get: Process returned value: 100
> PyBOMBS.Packager.source - WARNING - Cannot find a source URI for package ssl
> PyBOMBS.install_manager - ERROR - Error installing package ssl. Aborting.

any idea?
thank in advance

**Comment by mbr0wn** [comment]
Sorry, not sure what went wrong -- but it's some kind of issue in apt. If we can't figure out how to reproduce, there's nothing we can do about this.
