### ISSUE TITLE
Specifying a prefix path whose parent dir does not exist results in silent failure

### ISSUE THREAD

**Issue by courtarro** [gnuradio/pybombs#403]
With verbose enabled, we get:

    PyBOMBS - DEBUG - Can't create dir `/home/vagrant/sdr/main'. Parent directory does not exist.

However this message doesn't show up in non-verbose mode. Instead, PyBOMBS silently fails.

**Comment by mbr0wn** [comment]
Indeed an issue. Do you want to have a go at it?

**Comment by mbr0wn** [comment]
Actually this is pretty easy. I have a branch ready.
