### ISSUE TITLE
pi@raspberrypi:~ $ python Python 3.4.2 (

### ISSUE THREAD

**Issue by sincos364** [gnuradio/pybombs#408]

**Comment by sincos364** [comment]
pi@raspberrypi:~ $ python
Python 3.4.2 (default, Oct 19 2014, 13:31:11) 
[GCC 4.9.1] on linux
Type "help", "copyright", "credits" or "license" for more information.
[1]+  Stopped                 python
pi@raspberrypi:~ $ sudo pip install PyBOMBS
Downloading/unpacking PyBOMBS
  Downloading PyBOMBS-2.2.0.tar.gz (65kB): 65kB downloaded
  Running setup.py (path:/tmp/pip-build-so7iipb1/PyBOMBS/setup.py) egg_info for package PyBOMBS
    
Requirement already satisfied (use --upgrade to upgrade): setuptools in /usr/lib/python3/dist-packages (from PyBOMBS)
Downloading/unpacking PyYAML (from PyBOMBS)
  Downloading PyYAML-3.12.tar.gz (253kB): 253kB downloaded
  Running setup.py (path:/tmp/pip-build-so7iipb1/PyYAML/setup.py) egg_info for package PyYAML
    
Requirement already satisfied (use --upgrade to upgrade): requests in /usr/lib/python3/dist-packages (from PyBOMBS)
Requirement already satisfied (use --upgrade to upgrade): six in /usr/lib/python3/dist-packages (from PyBOMBS)
Downloading/unpacking future (from PyBOMBS)
  Downloading future-0.16.0.tar.gz (824kB): 824kB downloaded
  Running setup.py (path:/tmp/pip-build-so7iipb1/future/setup.py) egg_info for package future
    
    warning: no files found matching '*.au' under directory 'tests'
    warning: no files found matching '*.gif' under directory 'tests'
    warning: no files found matching '*.txt' under directory 'tests'
Installing collected packages: PyBOMBS, PyYAML, future
  Running setup.py install for PyBOMBS
    
    Installing pybombs script to /usr/local/bin
  Running setup.py install for PyYAML
    checking if libyaml is compilable
    arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.4m -c build/temp.linux-armv7l-3.4/check_libyaml.c -o build/temp.linux-armv7l-3.4/check_libyaml.o
    build/temp.linux-armv7l-3.4/check_libyaml.c:2:18: fatal error: yaml.h: Нет такого файла или каталога
     #include <yaml.h>
                      ^
    compilation terminated.
    
    libyaml is not found or a compiler error: forcing --without-libyaml
    (if libyaml is installed correctly, you may need to
     specify the option --include-dirs or uncomment and
     modify the parameter include_dirs in setup.cfg)
    
  Running setup.py install for future
    
    warning: no files found matching '*.au' under directory 'tests'
    warning: no files found matching '*.gif' under directory 'tests'
    warning: no files found matching '*.txt' under directory 'tests'
    Installing futurize script to /usr/local/bin
    Installing pasteurize script to /usr/local/bin
Successfully installed PyBOMBS PyYAML future
Cleaning up...

**Comment by mbr0wn** [comment]
Was this supposed to be an issue? Or a follow-up for the other RPi issue?
