### ISSUE TITLE
GNU Radio + Raspberry pi3

### ISSUE THREAD

**Issue by sincos364** [gnuradio/pybombs#409]
pi@raspberrypi:~ $ sudo pybombs -p gr-gsm install gr-gsm
PyBOMBS - INFO - PyBOMBS Version 2.2.0
PyBOMBS.install_manager - INFO - Phase 1: Creating install tree and installing binary packages:
Install tree:
|
\- gr-gsm
   |
   +- gr-osmosdr
   |  |
   |  +- airspy
   |  |
   |  +- hackrf
   |  |
   |  +- gnuradio
   |  |
   |  +- bladeRF
   |  |
   |  +- gr-iqbal
   |  |  |
   |  |  +- libosmo-dsp
   |  |  |
   |  |  \- gnuradio
   |  |
   |  +- osmo-sdr
   |  |
   |  \- rtl-sdr
   |
   \- gnuradio
PyBOMBS.install_manager - INFO - Phase 2: Recursively installing source packages to prefix:
PyBOMBS.install_manager - INFO - Installing package: gnuradio
PyBOMBS.Packager.source - WARNING - Build dir already exists: /usr/local/src/gnuradio/build
Building:    (100%) [=========================================================]
[  0%] Building ASM object volk/lib/CMakeFiles/volk_obj.dir/__/kernels/volk/asm/neon/volk_32f_x2_dot_prod_32f_neonasm_opts.s.o
/usr/local/src/gnuradio/volk/kernels/volk/asm/neon/volk_32f_x2_dot_prod_32f_neonasm_opts.s: Assembler messages:
/usr/local/src/gnuradio/volk/kernels/volk/asm/neon/volk_32f_x2_dot_prod_32f_neonasm_opts.s:46: Error: selected processor does not support ARM mode `sbfx r11,r1,#2,#1'
volk/lib/CMakeFiles/volk_obj.dir/build.make:1384: ошибка выполнения рецепта для цели «volk/lib/CMakeFiles/volk_obj.dir/__/kernels/volk/asm/neon/volk_32f_x2_dot_prod_32f_neonasm_opts.s.o»
make[2]: *** [volk/lib/CMakeFiles/volk_obj.dir/__/kernels/volk/asm/neon/volk_32f_x2_dot_prod_32f_neonasm_opts.s.o] Ошибка 1
CMakeFiles/Makefile2:233: ошибка выполнения рецепта для цели «volk/lib/CMakeFiles/volk_obj.dir/all»
make[1]: *** [volk/lib/CMakeFiles/volk_obj.dir/all] Ошибка 2
Makefile:147: ошибка выполнения рецепта для цели «all»
make: *** [all] Ошибка 2
PyBOMBS.Packager.source - ERROR - Build failed. See output above for error messages.
PyBOMBS.Packager.source - ERROR - Problem occurred while building package gnuradio:
Build failed.
PyBOMBS.install_manager - ERROR - Error installing package gnuradio. Aborting.

**Comment by mbr0wn** [comment]
This doesn't look like a PyBOMBS error. Also, I don't have the means to reproduce RPi bugs. We'll need to find someone to help fixing this things who has an RPi and is willing to debug these build errors.
