### ISSUE TITLE
Add auto-configuration

### ISSUE THREAD

**Issue by mbr0wn** [gnuradio/pybombs#411]
`pybombs config --auto` should run through steps to automatically determine a setup.

**Comment by mbr0wn** [comment]
It became `pybombs auto-config`.

**Comment by AGaikwad666** [comment]
Output of `pybombs auto-config` is:
PyBOMBS - INFO - PyBOMBS Version 2.3.2
PyBOMBS.RecipeListManager - ERROR - '/home/ubuntu/.pybombs/recipes/gr-etcetera' is not a directory.
PyBOMBS.auto-config - INFO - Using config file: None

Could you please help me with the error.

**Comment by marcusmueller** [comment]
Hi! This looks very much like an issue report? Could you open a new issue containing what you added as comment here?

**Comment by AGaikwad666** [comment]
ok. Thank you for your attention!
