### ISSUE TITLE
pybombs blocks not showing when installed

### ISSUE THREAD

**Issue by cyrus104** [gnuradio/pybombs#412]
I recently install pyboms and gnuradio with 5-6 packages to include gnuradio / companion, gr-foo, gr-ieee802-11 (not pybombs), gps, and several others.

I installed all but gr-ieee using sudo pip pybombs, when I run gnuradio-companion versus sudo gnuradio-companion I get different grc blocks in my list.

How am I able to get all of the grc block that were installed from all of the locations. I don't mind running sudo to run gnuradio-companion but need to be sure that all of the blocks are available.

Thanks

**Comment by mbr0wn** [comment]
This doesn't sound like a bug report, so I'm closing this. If you have follow-up questions please ask them in discuss-gnuradio, or #gnuradio. 

First, you should never have to run `sudo pybombs` anything, or `sudo gnuradio-companion`. To see all the blocks you installed via PyBOMBS, either run

    $ pybombs run gnuradio-companion

or go to your prefix, then enable the environment:

    $ cd /path/to/prefix
    $ source ./setupenv.sh
    $ gnuradio-companion

Your difference in blocks suggests you have multiple versions of GNU Radio installed. Maybe you have a version in `/usr/local` and another somewhere else. Make sure you have your installs sorted out, and don't have conflicting installs. Then, use GNU Radio from your prefix only.
