### ISSUE TITLE
Import Error: cannot import name qtgui

### ISSUE THREAD

**Issue by james-tate** [gnuradio/pybombs#417]
Running Pybombs on fresh OS install. When starting gnuradio-companion the qt gui widgets do not import. When trying to run the default .grc which gets generated when starting gnuradio-companion, I get an import error. 

top_block.py", line 26, in <module>
    from gnuradio import qtgui
ImportError: cannot import name qtgui

**Comment by james-tate** [comment]
It appears Pybombs does not handle the installation of QT4 and QWT. I ran Synaptic and searched for QWT. This installed QT4 as a prereq. I then ran "pybombs update gnuradio" and it enabled gr-qtgui support. In retrospect I guess pybombs rebuild would have worked as well.

**Comment by mbr0wn** [comment]
PyBOMBS *should* handle installing those though.

**Comment by james-tate** [comment]
Can confirm it does not seem to install gr-qtgui. I have tried on 2 separate machines using fresh installations of Mint 18.

**Comment by jahagirdar** [comment]
Seeing the same issue on centos 7

**Comment by tuf22191** [comment]
Hello resolution?
I am seeing this on Centos 7 too
