### ISSUE TITLE
should come with default set of recipes

### ISSUE THREAD

**Issue by marcusmueller** [gnuradio/pybombs#426]
Nearly every user will do 

    pybombs recipes add gr-recipes git+https://github.com/gnuradio/gr-recipes.git  
    pybombs recipes add gr-etcetera git+https://github.com/gnuradio/gr-etcetera.git

which is a copy-paste step we can avoid by either

1. having both repos instantiated (not necessarily synced) the moment a .pybombs is created
2. having a `pybombs recipes add-defaults` command.

Pro/cons:

* 1. is bad for the users that actually *don't* want the default repos, because those 0.5% need to `pybombs recipes remove`
* 2. is another step that we can avoid for 1-0.05 of users

**Comment by mbr0wn** [comment]
OK I give in. Moving discussion to PR.
