### ISSUE TITLE
PyBombs build error 

### ISSUE THREAD

**Issue by red-sabre** [gnuradio/pybombs#427]
receiving this error building, any help or pointing to a resource would be appreciated. Thanks!

[ 13%] Built target blocks_generated_includes
[ 28%] Built target gnuradio-blocks
[ 28%] Linking CXX executable test-gr-blocks
libgnuradio-blocks-3.7.12git.so.0.0.0: undefined reference to `.LFe10397'
collect2: error: ld returned 1 exit status
gr-blocks/lib/CMakeFiles/test-gr-blocks.dir/build.make:354: recipe for target 'gr-blocks/lib/test-gr-blocks' failed
make[2]: *** [gr-blocks/lib/test-gr-blocks] Error 1
CMakeFiles/Makefile2:2193: recipe for target 'gr-blocks/lib/CMakeFiles/test-gr-blocks.dir/all' failed
make[1]: *** [gr-blocks/lib/CMakeFiles/test-gr-blocks.dir/all] Error 2
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2
PyBOMBS.monitor_process() - DEBUG - Thread signaled termination or returned
PyBOMBS.monitor_process() - DEBUG - Return value: 2
PyBOMBS.Packager.source - ERROR - Build failed. See output above for error messages.
PyBOMBS.Packager.source - ERROR - Problem occurred while building package gnuradio:
Build failed.
PyBOMBS.install_manager - ERROR - Error installing package gnuradio. Aborting.

**Comment by mbr0wn** [comment]
There's a million possible reasons for this. Without a full log, and knowledge about your system, it's imposible to pinpoint. I would suggest taking this to discuss-gnuradio and provide some extra info about your system.
