### ISSUE TITLE
[R82XX] PLL not locked! 

### ISSUE THREAD

**Issue by jjbaek35** [gnuradio/pybombs#443]
Hi! all,
When I try to capture GSM signal, I faced following message,
and Wireshark can't capture any packets.
Please comment this

ubuntu@ubuntu:~$ sudo grgsm_livemon
linux; GNU C++ version 5.4.0 20160609; Boost_105800; UHD_003.009.006-0-g122d5f8e

gr-osmosdr v0.1.4-77-g2a2236cc (0.1.5git) gnuradio 3.7.11
built-in source types: file fcd rtl rtl_tcp uhd hackrf bladerf rfspace airspy redpitaya 
Using device #0 Realtek RTL2838UHIDIR SN: 00000001
Detached kernel driver
Found Rafael Micro R820T tuner
**[R82XX] PLL not locked!**
Exact sample rate is: 2000000.052982 Hz
**[R82XX] PLL not locked!**

ubuntu@ubuntu:~$ sudo wireshark -k -f udp -Y gsmtap -i lo

**Comment by mbr0wn** [comment]
This is not a PyBOMBS issue. Please report to the appropriate forums.
