### ISSUE TITLE
Recipe search directory order has changed

### ISSUE THREAD

**Issue by awalls-cx18** [gnuradio/pybombs#450]
The latest master has a change in behavior.  Previously pybombs would resolve recipes by looking in the recipe repos in the reverse order of how they were added (last repo added was first searched).  That has now changed to the first repo added is the first searched.  This is counter-intuitive when one has a repo intended to over-ride some recipes in gr-recipies.

**Comment by mbr0wn** [comment]
I wonder if it's because we moved to Ruamel YAML....

**Comment by mbr0wn** [comment]
Closing this and moving to the PR.
