### ISSUE TITLE
quickstart does not currently work

### ISSUE THREAD

**Issue by 777arc** [gnuradio/pybombs#456]
Currently if you install pybombs through pip, you get an older version and `pybombs recipes add-defaults` is not a supported command.  This might seem like a non-issue, but I think it's extremely important that gnuradio be easy to install (through pybombs), and that the pybombs quickstart works all the time.  Especially with GRCon coming up.

**Comment by zhudsonSM** [comment]
Had this exact problem. Until it is solved follow quickstart from before #447 here: https://github.com/gnuradio/pybombs/commit/4004f8c0d0727e9c64d85cd2f88935301f634e60?short_path=04c6e90#diff-04c6e90faac2675aa89e2176d2eec7d8

**Comment by 777arc** [comment]
Yeah, but most new people aren't going to be reading this issue, they will just jump to the conclusion that pybombs sucks =(

**Comment by mbr0wn** [comment]
OK I just tagged a 2.3.2 release with that feature.

**Comment by 777arc** [comment]
Nice, quickstart works for me now
