### ISSUE TITLE
Install older version of GnuRadio

### ISSUE THREAD

**Issue by peetersalong** [gnuradio/pybombs#461]
I would like to install specific gnuradio library release (3.7.10) using PyBombs. I have done following steps:

```
sudo pip install PyBOMBS
pybombs auto-config
pybombs recipes add gr-recipes git+https://github.com/gnuradio/gr-recipes.git
pybombs recipes add gr-etcetera git+https://github.com/gnuradio/gr-etcetera.git
mkdir /home/myuser/gnuradio
```

Now if I run `pybombs prefix init /home/myuser/gnuradio/prefix -a myprefix -R gnuradio-default` it will install the latest gnuradio. How could I install some older releases? I see that in the recipes file /home/myuser/.pybombs/recipes/gr-recipes/gnuradio.lwr i could set a branch, but is it possible to set a release tag?

My machine is running Ubuntu 16.04

**Comment by mbr0wn** [comment]
You can use `-R gnuradio-stable` for maint branches, or you simply do `pybombs config --package gnuradio gitrev $TAG` to specify a specific tag.
