### ISSUE TITLE
how to generate doxygen document after pybombs install?

### ISSUE THREAD

**Issue by ziyuanjun** [gnuradio/pybombs#464]
I use 
```
$ sudo pip install pybombs
$ pybombs recipes add gr-recipes git+https://github.com/gnuradio/gr-recipes.git
$ mkdir prefix/
$ pybombs prefix init -a default prefix/default/ -R gnuradio-default
```
and 
```
$ pybombs install gr-xxxxx
```
to install gnuradio and other blocks. But after installed successfully, I found that the doxygen documentations have not been generated. 
Is it the default option? Or, it just due to there's no `doxygen` and `xmlto`  in my OS when i run `pybombs` command?

After installed gnuradio, as well as  `doxygen` and `xmlto`, how to generate doxygen documentations?

**Comment by mbr0wn** [comment]
Please don't use the issue tracker for support questions. See `pybombs config builddocs`.
