### ISSUE TITLE
Package has no install method: python

### ISSUE THREAD

**Issue by 6vasia** [gnuradio/pybombs#468]
PyBOMBS.PackageManager - DEBUG - Checking if package python is installable...
PyBOMBS.Packager.portage - DEBUG - Package dev-lang/python has versions 3.4.5, 2.4.4 in portage
PyBOMBS.PackageManager - DEBUG - Package python is not installable.
PyBOMBS.install_manager - ERROR - Package has no install method: python
PyBOMBS - DEBUG - Unresolved install path.

using pybombs: d40b0b04

eix dev-lang/pyhon:
[I] dev-lang/python
     Available versions:  
     (2.7)  2.7.12 ~2.7.13
     (3.4)  3.4.5(3.4/3.4m) ~3.4.6(3.4/3.4m)
     (3.5)  ~3.5.3(3.5/3.5m)
     (3.6)  ~3.6.1-r1(3.6/3.6m)
Installed versions:  2.7.12(2.7) 3.4.5(3.4)

**Comment by mbr0wn** [comment]
Distro?

**Comment by 6vasia** [comment]
Oops, sorry. Gentoo.

**Comment by noc0lour** [comment]
@6vasia It looks like the check if python 2.7 is installed failed and python 2.7 then isn't listed as possible installation candidate.
