### ISSUE TITLE
cc1plus:Out of memory allocating

### ISSUE THREAD

**Issue by fzy139** [gnuradio/pybombs#481]
Hi,
I ran into this when building uhd on my raspbian.

It seems that the compiler should update to TDM-DCC as another post shows.

Is there any solution for this?

Pybombs 2.3.2
Thx!

**Comment by fzy139** [comment]
And I needn't uhd 'cause I'm using bladeRF.How to skip the branch  uhd to install?

**Comment by mbr0wn** [comment]
You can set environment variables to select other compilers. Typically, something like

    $ pybombs config --env CC <your-compiler>
