### ISSUE TITLE
Installing gr-op25 Fails

### ISSUE THREAD

**Issue by fonestar** [gnuradio/pybombs#483]
Hello getting the following Error while running:  "pybombs install gr-op25"

\- gr-op25
PyBOMBS.install_manager - INFO - Phase 2: Recursively installing source packages to prefix:
PyBOMBS.install_manager - INFO - Installing package: gr-op25
PyBOMBS.Packager.source - WARNING - Build dir already exists: /root/prefix/src/gr-op25/build
Building:    (100%) [===============================================================================================================================]
[ 24%] Built target gnuradio-op25
[ 27%] Built target test-op25
[ 28%] Built target _op25_swig_swig_tag
[ 30%] Built target _op25_swig_doc_tag
[ 35%] Built target pygen_op25_gr_op25_swig_13f8b
[ 40%] Built target _op25_swig
[ 42%] Built target pygen_op25_gr_op25_python_87f89
[ 42%] Built target pygen_op25_gr_op25_apps_383eb
[ 61%] Built target imbe_vocoder
[ 62%] Building CXX object op25/gr-op25_repeater/lib/CMakeFiles/gnuradio-op25_repeater.dir/p25_frame_assembler_impl.cc.o
/root/prefix/src/gr-op25/op25/gr-op25_repeater/lib/p25_frame_assembler_impl.cc: In member function ‘void gr::op25_repeater::p25_frame_assembler_impl::p25p2_queue_msg(int)’:
/root/prefix/src/gr-op25/op25/gr-op25_repeater/lib/p25_frame_assembler_impl.cc:42:41: error: narrowing conversion of ‘255’ from ‘int’ to ‘char’ inside { } [-Wnarrowing]
  static const char wbuf[2] = {0xff, 0xff}; // dummy NAC
                                         ^
/root/prefix/src/gr-op25/op25/gr-op25_repeater/lib/p25_frame_assembler_impl.cc:42:41: error: narrowing conversion of ‘255’ from ‘int’ to ‘char’ inside { } [-Wnarrowing]
op25/gr-op25_repeater/lib/CMakeFiles/gnuradio-op25_repeater.dir/build.make:206: recipe for target 'op25/gr-op25_repeater/lib/CMakeFiles/gnuradio-op25_repeater.dir/p25_frame_assembler_impl.cc.o' failed
make[2]: *** [op25/gr-op25_repeater/lib/CMakeFiles/gnuradio-op25_repeater.dir/p25_frame_assembler_impl.cc.o] Error 1
CMakeFiles/Makefile2:682: recipe for target 'op25/gr-op25_repeater/lib/CMakeFiles/gnuradio-op25_repeater.dir/all' failed
make[1]: *** [op25/gr-op25_repeater/lib/CMakeFiles/gnuradio-op25_repeater.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
PyBOMBS.Packager.source - ERROR - Build failed. See output above for error messages.
PyBOMBS.Packager.source - ERROR - Problem occurred while building package gr-op25:
Build failed.
PyBOMBS.install_manager - ERROR - Error installing package gr-op25. Aborting.

**Comment by mbr0wn** [comment]
This looks like a bug in gr-op25, not in PyBOMBS.
