### ISSUE TITLE
PyBOMBS.RecipeListManager - ERROR - '/home/ubuntu/.pybombs/recipes/gr-etcetera' is not a directory

### ISSUE THREAD

**Issue by AGaikwad666** [gnuradio/pybombs#497]
I am trying to install GNURadio using pybombs on Ubuntu 14.04 LTS. I am following the steps given here:https://github.com/gnuradio/pybombs/blob/master/README.md [](url)
when I run` $ pybombs auto-config` I am getting output as:
PyBOMBS - INFO - PyBOMBS Version 2.3.2
PyBOMBS.RecipeListManager - ERROR - '/home/ubuntu/.pybombs/recipes/gr-etcetera' is not a directory.
PyBOMBS.auto-config - INFO - Using config file: None

Please help me with the error.

**Comment by mbr0wn** [comment]
I guess this must have been fixed -- it seems to work fine on master.
