### ISSUE TITLE
Rebuild Module

### ISSUE THREAD

**Issue by bigtree123321** [gnuradio/pybombs#501]
I have changed something in OFDM Carrier Allocator module under the path ~/prefix/src/gnuradio/gr-digital/lib

but I don't know how to rebuilt it by pybombs.

Thanks for any reply.

**Comment by swap-nil7** [comment]
@bigtree123321: You can post such doubts on IRC channel. 
Maybe `pybombs rebuild ~/prefix gnuradio -k` will work.

**Comment by mbr0wn** [comment]
@swap-nil7 is correct (and thanks for responding, @swap-nil7!).
