### ISSUE TITLE
fails to install gr-mapper

### ISSUE THREAD

**Issue by CDVyhlidal** [gnuradio/pybombs#521]
I am using Ubuntu 18.04. The following occurs when attempting to install gr-mapper.

$ pybombs install gr-mapper
PyBOMBS.ConfigManager - INFO - Prefix Python version is: 2.7.15
PyBOMBS - INFO - PyBOMBS Version 2.3.3a0
PyBOMBS.install_manager - INFO - Phase 1: Creating install tree and installing binary packages:
PyBOMBS.get_recipe - ERROR - Error fetching recipe `g':
Package g has no recipe file!
I was able to install gr-radar and gr-cdma with no problems, so I am unsure if it is a problem with pybombs or gr-mapper.

**Comment by mbr0wn** [comment]
```
$ pybombs lint .pybombs/recipes/gr-recipes/gr-mapper.lwr
[INFO] Prefix Python version is: 2.7.15
[INFO] PyBOMBS Version 2.3.4a0
Linting recipe `.pybombs/recipes/gr-recipes/gr-mapper.lwr'
[HMM] - No satisfy rules declared
[VERY BAD] Dependencies is not a list: gnuradio
```

The recipe is/was broken.
