### ISSUE TITLE
pybombs install 3.7.13.5 instead 3.8

### ISSUE THREAD

**Issue by mohmmadd** [gnuradio/pybombs#547]
When I try to install GNU Radio with these codes:
```
$ mkdir ~/prefix
$ pybombs prefix init -a default ~/prefix/default/ -R gnuradio-default
```
It installs 3.7.13.5 instead 3.8. 
What should I do to install 3.8?

**Comment by velichkov** [comment]
Hi @mohmmadd, @ikarus23,

> When I try to install GNU Radio with these codes:
> 
> ```
> $ mkdir ~/prefix
> $ pybombs prefix init -a default ~/prefix/default/ -R gnuradio-default
> ```
> 
> It installs 3.7.13.5 instead 3.8.
> What should I do to install 3.8?

You need to do some modifications to the recipes and then install from gnuradio38 recipe. See https://github.com/gnuradio/gr-recipes/pull/155

**Comment by ikarus23** [comment]
Ok, makes sense that this is a recipe issue. I think we can close this here and continue over at https://github.com/gnuradio/gr-recipes/.

**Comment by mbr0wn** [comment]
You can `pybombs install gnuradio37`.

**Comment by mbr0wn** [comment]
@mohmmadd to fix, run `pybombs recipes update`
