### ISSUE TITLE
Wrong PYTHONPATH in setup_env.sh

### ISSUE THREAD

**Issue by ikarus23** [gnuradio/pybombs#552]
Hi, when I use fresh installation of pybombs on Ubuntu 18.04 LTS the `PYTHONPATH` in the `setup_env.sh` seams wrong. What I did was:
```
sudo pip install pybombs
pybombs auto-config
pybombs recipes add-defaults
pybombs prefix init ~/prefix -a myprefix -R gnuradio-default
source ~/prefix/setup_env.sh
gnuradio-companion
```
But `gnuradio-companion` raises an error because the module `gnuradio` was not found. My `PYTHONPATH` in the generated `setup_env.sh` is
```
/home/sdr/prefix/python:/home/sdr/prefix/lib/python2.6/site-packages:/home/sdr/prefix/lib64/python2.6/site-packages:/home/sdr/prefix/lib/python2.6/dist-packages:/home/sdr/prefix/lib64/python2.6/dist-packages:/home/sdr/prefix/lib/python2.7/site-packages:/home/sdr/prefix/lib64/python2.7/site-packages:/home/sdr/prefix/lib/python2.7/dist-packages:/home/sdr/prefix/lib64/python2.7/dist-packages:
```
No hint of python3. Is that still correct? I've installed Gnuradio 3.8. Also, there are no folders like `/home/sdr/prefix/python` and `/home/sdr/prefix/lib/python2.6`. But there is an `prefix/lib/python2.7`, `prefix/lib/python3` and `prefix/lib/python3.6`.

What happened here? Is the generated `setup_env.sh` wrong?

**Comment by mbr0wn** [comment]
Yup, it's wrong. We have a fix on master -- more of a hack, really. But it's an improvement.
