### ISSUE TITLE
Pybombs fails to install GNURadio 3.8 on Ubuntu 18.04

### ISSUE THREAD

**Issue by danalvarez** [gnuradio/pybombs#579]
Hello everyone:

Posting this here because I cannot seem to find any solution online, been trying this on and off for several weeks.

So **I have a working installation of GNURadio 3.7 on the `default/` prefix**. I did this with Pybombs and no issues after working out some quirks. I want to give 3.8 a try so I've been trying to install this into a new prefix, but it just doesn't work. I feel like the error is kind of obscure, I don't know what it relates to. 

Always fails after `[ 39%] Building CXX object gr-blocks/swig/CMakeFiles/blocks_swig0.dir/CMakeFiles/blocks_swig0.dir/blocks_swig0PYTHON_wrap.cxx.o`. The error in the end appears to be:

```
gr-blocks/swig/CMakeFiles/blocks_swig0.dir/build.make:82: recipe for target 'gr-blocks/swig/CMakeFiles/blocks_swig0.dir/CMakeFiles/blocks_swig0.dir/blocks_swig0PYTHON_wrap.cxx.o' failed
make[2]: *** [gr-blocks/swig/CMakeFiles/blocks_swig0.dir/CMakeFiles/blocks_swig0.dir/blocks_swig0PYTHON_wrap.cxx.o] Error 1
CMakeFiles/Makefile2:7023: recipe for target 'gr-blocks/swig/CMakeFiles/blocks_swig0.dir/all' failed
make[1]: *** [gr-blocks/swig/CMakeFiles/blocks_swig0.dir/all] Error 2
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2
[ERROR] Build failed. See output above for error messages.
[ERROR] Problem occurred while building package gnuradio:
Build failed.
[ERROR] Error installing package gnuradio. Aborting.

```
I'm attaching a full [log.txt](https://github.com/gnuradio/pybombs/files/4841665/log.txt) of the output...

Running `pybombs inv` after the failed installation shows:
```
[INFO] Prefix Python version is: 3.6.9
[INFO] PyBOMBS Version 2.3.4a0
Showing package state:
uhd:                installed
gnuradio:           configured
```

Running `pybombs inv` in the `default/` prefix shows:

```
[INFO] Prefix Python version is: 3.6.9
[INFO] PyBOMBS Version 2.3.4a0
Showing package state:
uhd:                installed
gnuradio:           installed
pyconstruct:        installed
libfec:             installed
gr-satellites37:    installed
gr-gpredict-doppler37:installed
rtl-sdr:            installed
hackrf:             installed
osmo-sdr:           installed
gr-osmosdr37:       installed
gr-msgtools:        installed
gr-sattools:        installed
```

## Steps to reproduce

1. Install GNURadio 3.7 into `default/` prefix
2. `pybombs prefix init ~/prefix/gr38 -R gnuradio-default`

I appreciate anyone's input on this... I feel stumped and don't know what else to search for.

Best wishes,

Dan

**Comment by dkozel** [comment]
> [WARNING] A source build for package gnuradio was requested, but binary install was found!
Install gnuradio from source despite binary install available Y/[N]? y

Do you know where this binary version is? If you have a system wide version of GNU Radio installed 3.8 cannot be built into a prefix due to a bug as far as I can remember.

**Comment by danalvarez** [comment]
Hey, @dkozel !

Thanks for the very quick response... You're completely right. I had installed GQRX via apt-get and this installs GNURadio system wide. I've removed it and now Pybombs correctly built 3.8 into the desired prefix.

Thanks!!!
