### ISSUE TITLE
e

### ISSUE THREAD

**Issue by RubioHernan** [gnuradio/pybombs#593]
Before posting an issue, please check the following:

- [ ] Is this actually a bug in PyBOMBS, or is it a bug in the package you're
      installing? If it's the latter, this is the wrong place to post. It won't
      get fixed unless the author of the package is informed.

- [ ] How can this issue be reproduced? We have Docker-based tests for various
      Linux distributions, which are the reference for whether or not we
      consider a specific distribution as functional. Have you provided
      instructions to reproduce?

- [ ] Have you included all relevant logs to help developers find the issue?
      Did you bump the verbosity (`-v` or `-vv`)?

**Comment by argilo** [comment]
It seems like this was opened in error, so I'll close it off.
