### ISSUE TITLE
SWIG Error installing GNURadio3.8 with Pybombs

### ISSUE THREAD

**Issue by nbulk** [gnuradio/pybombs#610]
Trying to install GNURadio via pybombs.
Following the commands in the readme.

After hitting pybombs prefix init ~/prefix-3.8 -R gnuradio-default the process ends with a build error.
Last output from the process:

Scanning dependencies of target blocks_swig3
[ 30%] Building CXX object gr-blocks/swig/CMakeFiles/blocks_swig3.dir/CMakeFiles/blocks_swig3.dir/blocks_swig3PYTHON_wrap.cxx.o
make[2]: *** [gr-blocks/swig/CMakeFiles/blocks_swig3.dir/build.make:63: gr-blocks/swig/CMakeFiles/blocks_swig3.dir/CMakeFiles/blocks_swig3.dir/blocks_swig3PYTHON_wrap.cxx.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:5950: gr-blocks/swig/CMakeFiles/blocks_swig3.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
[DEBUG] Thread signaled termination or returned
[DEBUG] Return value: 2
[ERROR] Build failed. See output above for error messages.
[ERROR] Problem occurred while building package gnuradio: Build failed.
[ERROR] Error installing package gnuradio. Aborting.

**Comment by willcode** [comment]
It looks like you ran out of memory while compiling the SWIG wrappers. Try setting `makewidth: 1` in your `$HOME/.pybombs/config.yml`, or at least set it to something smaller than it is now.
