### ISSUE TITLE
C port is not detected by pybomb 

### ISSUE THREAD

**Issue by SuhailAhamedlearner** [gnuradio/pybombs#623]
My laptop only supports 100MBPS Which made me to use a C hub adapter to connect N210 with my laptop via C port. 

Now the issue is when I build UHD from source, it can detect the N210 device even when it is connected via type C port in laptop. BUT in pybomb, the N210 is not detected when I connect via C port using an adaptor. 

Can anyone help me on this matter ?? 

Thanks in advance.

**Comment by willcode** [comment]
This issue tracker is used for PyBOMBS bugs and feature requests. PyBOMBS is a build system, not a program, so this is not related to PyBOMBS. As a guess, you have have multiple installations and need to figure out how to set up paths. For general help, try the USRP mailing list. If you are using GNU Radio, also try the GNU Radio mailing list or chat.gnuradio.org.
