### ISSUE TITLE
gqrx fails to install on Ubuntu 14.04

### ISSUE THREAD

**Issue by argilo** [gnuradio/pybombs#72]
I just tried installing gqrx on Ubuntu 14.04 and it failed with the following error:

g++ -m64 -Wl,-O1 -o gqrx main.o mainwindow.o receiver.o remote_control.o remote_control_settings.o cafsk12.o costabf.o agc_impl.o correct_iq_cc.o lpf.o resampler_xx.o rx_demod_am.o rx_demod_fm.o rx_fft.o rx_filter.o rx_meter.o rx_agc_xx.o rx_noise_blanker_cc.o sniffer_f.o stereo_demod.o udp_sink_f.o afsk1200win.o agc_options.o audio_options.o demod_options.o dockinputctl.o dockaudio.o dockfft.o dockrxopt.o freqctrl.o ioconfig.o meter.o nb_options.o plotter.o qtcolorpicker.o nbrx.o receiver_base.o wfmrx.o iq_tool.o pa_device_list.o pa_sink.o pa_source.o moc_mainwindow.o moc_remote_control.o moc_remote_control_settings.o moc_cafsk12.o moc_afsk1200win.o moc_agc_options.o moc_audio_options.o moc_demod_options.o moc_dockaudio.o moc_dockfft.o moc_dockinputctl.o moc_dockrxopt.o moc_freqctrl.o moc_ioconfig.o moc_meter.o moc_nb_options.o moc_plotter.o moc_qtcolorpicker.o moc_iq_tool.o qrc_icons.o qrc_textfiles.o    -L/usr/lib/x86_64-linux-gnu -lboost_system-mt -lboost_program_options-mt -lrt -lpulse-simple -lpulse -L/home/argilo/git/target/lib -lgnuradio-analog -lgnuradio-filter -lgnuradio-fft -lgnuradio-osmosdr -lgnuradio-blocks -lgnuradio-runtime -lgnuradio-pmt -lQtSvg -lQtGui -lQtNetwork -lQtCore -lpthread 
/usr/bin/ld: cannot find -lboost_system-mt
/usr/bin/ld: cannot find -lboost_program_options-mt
collect2: error: ld returned 1 exit status
make: *** [gqrx] Error 1
ERROR:root:PyBOMBS Make step failed for package (gqrx) please see bash output above for a reason (hint: look for the word Error)

**Comment by pierce403** [comment]
I just ran into this issue on Ubuntu 14.10, so it's still present.
Hacked out the -mt from the recipe to get past it, but now I'm stuck on #102

Maybe some sort of warning message could be displayed before trying to use recipes that contain known bugs?

**Comment by mbr0wn** [comment]
@pierce403, you're making it sound like we push known bugs on purpose to people. If we have recipes with known bugs, the correct solution is to fix the bugs, not push a change to a file that lists known bugs. -mt is not wrong per se, but you might have to remove it.

**Comment by jmcorgan** [comment]
Yeah, I do have to patch out the -mt when building the live SDR image for
ubuntu 14.04.  Not sure why but easy enough work around.

On Friday, March 20, 2015, mbr0wn <notifications@github.com> wrote:

> @pierce403 <https://github.com/pierce403>, you're making it sound like we
> push known bugs on purpose to people. If we have recipes with known bugs,
> the correct solution is to fix the bugs, not push a change to a file that
> lists known bugs. -mt is not wrong per se, but you might have to remove it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gnuradio/pybombs/issues/72#issuecomment-84153468>.
>


-- 
Johnathan Corgan
Corgan Labs - SDR Training and Development Services
http://corganlabs.com

**Comment by hubert3** [comment]
Hit the same error on Ubuntu 14.10 fresh install as of April 2015

**Comment by ckuethe** [comment]
Fixed with https://github.com/gnuradio/recipes/pull/38
